#pragma once

// Handy macros to just refer to events by their names.
#define broin ev[Event::broin]
#define cycin ev[Event::cycin]
#define sldin ev[Event::sldin]
#define xbin ev[Event::xbin]
#define xcin ev[Event::xcin]
#define xbhin ev[Event::xbhin]
#define forin ev[Event::forin]
#define curin ev[Event::curin]
#define mntin ev[Event::mntin]
#define lntin ev[Event::lntin]
#define matin ev[Event::matin]
#define cndin ev[Event::cndin]
#define bint ev[Event::bint]
#define brnin ev[Event::brnin]
#define fusin ev[Event::fusin]
#define ledin ev[Event::ledin]
#define safin ev[Event::safin]
#define vlgin ev[Event::vlgin]
#define gnoin ev[Event::gnoin]
#define bckin ev[Event::bckin]
#define sphin ev[Event::sphin]
#define sclin ev[Event::sclin]
#define egher ev[Event::egher]
#define zgnin ev[Event::zgnin]
#define zglin ev[Event::zglin]
#define folin ev[Event::folin]
#define mrint ev[Event::mrint]
#define pinin ev[Event::pinin]
#define inqin ev[Event::inqin]
#define strte ev[Event::strte]
