// Generated at 06-24-24 11:28:58
#pragma once
const GObjectDefinition gobjects[] = {
{Bits::numbits, { "IT", "THAT", "THIS", "HIM" }, 
    {  }, 
    "random object", 
    { Bits::ovison, Bits::ndescbit } },
{Bits::numbits, { "GBROC", "BROCH", "MAIL" }, 
    { "FREE" }, 
    "free brochure", 
    { Bits::ovison } ,
    obj_funcs::brochure()},
{Bits::numbits, { "#####", "ME", "CRETI", "MYSEL", "SELF" }, 
    {  }, 
    "cretin", 
    { Bits::ovison, Bits::villain } ,
    obj_funcs::cretin(), 
    { }, 
    { OP(ObjectSlots::ksl_oglobal, 0), OP(ObjectSlots::ksl_oactor, e_oactor::player) }},
{Bits::numbits, { "WISH", "BLESS" }, 
    {  }, 
    "wish", 
    { Bits::ovison, Bits::ndescbit } },
{Bits::numbits, { "EVERY", "ALL" }, 
    {  }, 
    "everything", 
    { Bits::ovison, Bits::takebit, Bits::ndescbit, Bits::no_check_bit, Bits::bunchbit } ,
    obj_funcs::valuables_c()},
{Bits::numbits, { "POSSE" }, 
    {  }, 
    "possessions", 
    { Bits::ovison, Bits::takebit, Bits::ndescbit, Bits::no_check_bit, Bits::bunchbit } ,
    obj_funcs::valuables_c()},
{Bits::numbits, { "VALUA", "TREAS" }, 
    {  }, 
    "valuables", 
    { Bits::ovison, Bits::takebit, Bits::ndescbit, Bits::no_check_bit, Bits::bunchbit } ,
    obj_funcs::valuables_c()},
{Bits::numbits, { "SAILO" }, 
    {  }, 
    "sailor", 
    { Bits::ovison, Bits::ndescbit } },
{Bits::numbits, { "TEETH" }, 
    {  }, 
    "set of teeth", 
    { Bits::ovison, Bits::ndescbit } },
{Bits::numbits, { "WALL", "WALLS" }, 
    {  }, 
    "wall", 
    { Bits::ovison } ,
    obj_funcs::wall_function()},
{Bits::numbits, { "GWALL", "WALL" }, 
    { "GRANI" }, 
    "granite wall", 
    { Bits::ovison } ,
    obj_funcs::granite()},
{Bits::numbits, { "GROUN", "EARTH", "SAND" }, 
    {  }, 
    "ground", 
    { Bits::ovison, Bits::digbit } ,
    obj_funcs::ground_function()},
{Bits::numbits, { "GRUE" }, 
    {  }, 
    "lurking grue", 
    { Bits::ovison } ,
    obj_funcs::grue_function()},
{Bits::numbits, { "HANDS", "HAND" }, 
    { "BARE" }, 
    "pair of hands", 
    { Bits::ovison, Bits::ndescbit, Bits::toolbit } },
{Bits::numbits, { "LUNGS", "AIR" }, 
    {  }, 
    "breath", 
    { Bits::ovison, Bits::ndescbit, Bits::toolbit } },
{Bits::numbits, { "AVIAT", "FLYER" }, 
    {  }, 
    "flyer", 
    { Bits::ovison, Bits::ndescbit } },
{Bits::numbits, { "EXCEP", "BUT" }, 
    {  }, 
    "moby lossage", 
    { Bits::ovison, Bits::ndescbit } },
{Bits::wellbit, { "WELL" }, 
    { "MAGIC" }, 
    "well", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::well_function()},
{Bits::ropebit, { "SROPE", "ROPE", "PIECE" }, 
    {  }, 
    "piece of rope", 
    { Bits::ovison, Bits::climbbit, Bits::no_check_bit } ,
    obj_funcs::slide_rope()},
{Bits::slidebit, { "SLIDE", "CHUTE" }, 
    {  }, 
    "chute", 
    { Bits::ovison} ,
    obj_funcs::slide_function()},
{Bits::cpwall, { "CPEWL", "WALL" }, 
    { "EAST", "EASTE" }, 
    "eastern wall", 
    { Bits::ovison} ,
    obj_funcs::cpwall_object()},
{Bits::cpwall, { "CPWWL", "WALL" }, 
    { "WEST", "WESTE" }, 
    "western wall", 
    { Bits::ovison} ,
    obj_funcs::cpwall_object()},
{Bits::cpwall, { "CPSWL", "WALL" }, 
    { "SOUTH" }, 
    "southern wall", 
    { Bits::ovison} ,
    obj_funcs::cpwall_object()},
{Bits::cpwall, { "CPNWL", "WALL" }, 
    { "NORTH" }, 
    "northern wall", 
    { Bits::ovison} ,
    obj_funcs::cpwall_object()},
{Bits::cpladder, { "CPLAD", "LADDE" }, 
    {  }, 
    "ladder", 
    { Bits::ovison} ,
    obj_funcs::cpladder_object()},
{Bits::birdbit, { "BIRD", "SONGB" }, 
    { "SONG" }, 
    "bird", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::bird_object()},
{Bits::housebit, { "HOUSE" }, 
    { "WHITE" }, 
    "white house", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::house_function()},
{Bits::treebit, { "TREE" }, 
    {  }, 
    "tree", 
    { Bits::ovison, Bits::ndescbit } },
{Bits::guardbit, { "GUARD" }, 
    {  }, 
    "Guardian of Zork", 
    { Bits::ovison, Bits::vicbit, Bits::villain } ,
    obj_funcs::guardians()},
{Bits::rosebit, { "ROSE", "COMPA" }, 
    {  }, 
    "compass rose", 
    { Bits::ovison } },
{Bits::masterbit, { "MASTE", "KEEPE", "DUNGE" }, 
    { "DUNGE" }, 
    "dungeon master", 
    { Bits::ovison, Bits::vicbit, Bits::actorbit } ,
    obj_funcs::master_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "The dungeon master is quietly leaning on his staff here."), OP(ObjectSlots::ksl_oactor, e_oactor::master), OP(ObjectSlots::ksl_oglobal, 0) }},
{Bits::mirrorbit, { "MIRRO", "STRUC" }, 
    {  }, 
    "mirror", 
    { Bits::ovison } ,
    obj_funcs::mirror_function()},
{Bits::panelbit, { "PANEL" }, 
    {  }, 
    "panel", 
    { Bits::ovison } ,
    obj_funcs::panel_function()},
{Bits::chanbit, { "CHANN" }, 
    {  }, 
    "stone channel", 
    { Bits::ovison } },
{Bits::wall_eswbit, { "WEAST", "WALL" }, 
    { "EAST", "EASTE" }, 
    "eastern wall", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::scolwall()},
{Bits::wall_eswbit, { "WSOUT", "WALL" }, 
    { "SOUTH" }, 
    "southern wall", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::scolwall()},
{Bits::wall_eswbit, { "WWEST", "WALL" }, 
    { "WEST", "WESTE" }, 
    "western wall", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::scolwall()},
{Bits::wall_nbit, { "WNORT", "WALL" }, 
    { "NORTH" }, 
    "northern wall", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::scolwall()},
{Bits::rgwater, { "GWATE", "WATER", "QUANT", "LIQUI", "H2O" }, 
    {  }, 
    "water", 
    { Bits::drinkbit, Bits::ovison } ,
    obj_funcs::water_function()},
{Bits::dwindow, { "DWIND" }, 
    {  }, 
    "window", 
    { Bits::ovison} ,
    nullptr},
};
