#include "stdafx.h"
#include "info.h"

const std::string_view info_str = "Welcome to Zork!\n\n"
"You are near a large dungeon, which is reputed to contain vast\n"
"quantities of treasure.  Naturally, you wish to acquire some of it.\n"
"In order to do so, you must of course remove it from the dungeon.  To\n"
"receive full credit for it, you must deposit it safely in the trophy\n"
"case in the living room of the house.\n\n"
"In addition to valuables, the dungeon contains various objects\n"
"which may or may not be useful in your attempt to get rich.  You may\n"
"need sources of light, since dungeons are often dark, and weapons,\n"
"since dungeons often have unfriendly things wandering about.  Reading\n"
"material is scattered around the dungeon as well;  some of it\n"
"is rumored to be useful.\n\n"
"To determine how successful you have been, a score is kept.\n"
"When you find a valuable object and pick it up, you receive a\n"
"certain number of points, which depends on the difficulty of finding\n"
"the object.  You receive extra points for transporting the treasure\n"
"safely to the living room and placing it in the trophy case.  In\n"
"addition, some particularly interesting rooms have a value associated\n"
"with visiting them.  The only penalty is for getting yourself killed,\n"
"which you may do only twice.\n\n"
"Of special note is a thief (always carrying a large bag) who\n"
"likes to wander around in the dungeon (he has never been seen by the\n"
"light of day).  He likes to take things.  Since he steals for pleasure\n"
"rather than profit and is somewhat sadistic, he only takes things which\n"
"you have seen.  Although he prefers valuables, sometimes in his haste\n"
"he may take something which is worthless.  From time to time, he examines\n"
"his take and discards objects which he doesn't like.  He may occas-\n"
"ionally stop in a room you are visiting, but more often he just wanders\n"
"through and rips you off (he is a skilled pickpocket).\n";

const std::string_view help_str =
{
    "Useful commands:\n\n"

"   The 'BRIEF' command suppresses printing of long room descriptions\n"
"for rooms which have been visited.  The 'SUPERBRIEF' command suppresses\n"
"printing of long room descriptions for all rooms.  The 'VERBOSE'\n"
"command restores long descriptions.\n"
"   The 'INFO' command prints information which might give some idea\n"
"of what the game is about.\n"
"   The 'QUIT' command prints your score and asks whether you wish\n"
"to continue playing.\n"
"   The 'SAVE' command saves the state of the game for later continuation.\n"
"   The 'RESTORE' command restores a saved game.\n"
"   The 'INVENTORY' command lists the objects in your possession.\n"
"   The 'LOOK' command prints a description of your surroundings.\n"
"   The 'SCORE' command prints your current score and ranking.\n"
"   The 'TIME' command tells you how long you have been playing.\n"
"   The 'DIAGNOSE' command reports on your injuries, if any.\n\n"
"Command abbreviations:\n\n"
"   The 'INVENTORY' command may be abbreviated 'I'.\n"
"   The 'LOOK' command may be abbreviated 'L'.\n"
"   The 'QUIT' command may be abbreviated 'Q'.\n\n"
"Containment :\n\n"

"   Some objects can contain other objects.Many such containers can\n"
"be opened and closed.  The rest are always open.  They may or may\n"
"not be transparent.  For you to access (e.g., take) an object\n"
"which is in a container, the container must be open.  For you\n"
"to see such an object, the container must be either open or\n"
"transparent.  Containers have a capacity, and objects have sizes;\n"
"the number of objects which will fit therefore depends on their\n"
"sizes.  You may put any object you have access to (it need not be\n"
"in your hands) into any other object.  At some point, the program\n"
"will attempt to pick it up if you don't already have it, which\n"
"process may fail if you're carrying too much.  Although containers\n"
"can contain other containers, the program doesn't access more than\n"
"one level down.\n\n"
"Fighting:\n\n"
"   Occupants of the dungeon will, as a rule, fight back when\n"
"attacked.  In some cases, they may attack even if unprovoked.\n"
"Useful verbs here are 'ATTACK <villain> WITH <weapon>', 'KILL',\n"
"etc.  Knife - throwing may or may not be useful.  You have a\n"
"fighting strength which varies with time.  Being in a fight,\n"
"getting killed, and being injured all lower this strength.\n"
"Strength is regained with time.  Thus, it is not a good idea to\n"
"fight someone immediately after being killed.  Other details\n"
"should become apparent after a few melees or deaths.\n\n"
"Command parser:\n\n"
"   A command is one line of text terminated by a carriage return.\n"
"For reasons of simplicity, all words are distinguished by their\n"
"first five letters.  All others are ignored.  For example, typing\n"
"'DISASSEMBLE THE ENCYCLOPEDIA' is not only meaningless, it also\n"
"creates excess effort for your fingers.  Note that this trunca-\n"
"tion may produce ambiguities in the interpretation of longer words.\n\n"
"You are dealing with a fairly stupid parser, which understands\n"
"the following types of things--\n\n"
"   Actions:\n"
"        Among the more obvious of these, such as TAKE, PUT, DROP, etc.\n"
"        Fairly general forms of these may be used, such as PICK UP,\n"
"        PUT DOWN, etc.\n\n"

"   Directions:\n"
"        NORTH, SOUTH, UP, DOWN, etc. and their various abbreviations.\n"
"        Other more obscure directions (LAND, CROSS) are appropriate in\n"
"        only certain situations.\n\n"
"   Objects:\n"
"        Most objects have names and can be referenced by them.\n\n"
"   Adjectives:\n"
"        Some adjectives are understood and required when there are\n"
"        two objects which can be referenced with the same 'name' (e.g.,\n"
"        DOORs, BUTTONs).\n\n"
"   Prepositions:\n"
"        It may be necessary in some cases to include prepositions, but\n"
"        the parser attempts to handle cases which aren't ambiguous\n"
"        without.  Thus 'GIVE CAR TO DEMON' will work, as will 'GIVE DEMON\n"
"        CAR'.  'GIVE CAR DEMON' probably won't do anything interesting.\n"
"        When a preposition is used, it should be appropriate;  'GIVE CAR\n"
"        WITH DEMON' won't parse.\n\n"
"   Sentences:\n"
"        The parser understands a reasonable number of syntactic construc-\n"
"        tions.  In particular, multiple commands (separated by periods)\n"
"        can be placed on the same line.\n\n"
"   Ambiguity:\n"
"        The parser tries to be clever about what to do in the case of\n"
"        actions which require objects that are not explicitly specified.\n"
"        If there is only one possible object, the parser will assume\n"
"        that it should be used.  Otherwise, the parser will ask.\n"
"        Most questions asked by the parser can be answered."
};