// Generated at 06-24-24 11:28:58
#pragma once
const ObjectDefinition objects[] = {
{{ "BUTTO" }, 
    {  }, 
    "", 
    { }},
{{ "!!!!!" }, 
    {  }, 
    "", 
    { }},
{{ "GHOST", "SPIRI", "FIEND" }, 
    {  }, 
    "number of ghosts", 
    { Bits::ovison, Bits::vicbit } ,
    obj_funcs::ghost_function()},
{{ "GATES", "GATE" }, 
    {  }, 
    "gates", 
    { }},
{{ "FBASK", "CAGE", "DUMBW", "BASKE" }, 
    { "LOWER" }, 
    "lowered basket", 
    { Bits::ovison } ,
    obj_funcs::dumbwaiter()},
{{ "FOOD", "SANDW", "LUNCH", "DINNE" }, 
    { "HOT", "PEPPE" }, 
    "lunch", 
    { Bits::ovison, Bits::takebit, Bits::foodbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "A hot pepper sandwich is here.") }},
{{ "TBAR", "T-BAR", "BAR" }, 
    { "T" }, 
    "T-bar", 
    { Bits::ovison, Bits::ndescbit } },
{{ "GNOME", "TROLL" }, 
    { "VOLCA" }, 
    "Volcano Gnome", 
    { Bits::ovison, Bits::vicbit } ,
    obj_funcs::gnome_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a nervous Volcano Gnome here.") }},
{{ "BAGCO", "BAG", "COINS" }, 
    { "OLD", "LEATH" }, 
    "bag of coins", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "An old leather bag, bulging with coins, is here."), OP(ObjectSlots::ksl_osize, 15), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_otval, 5) }},
{{ "BARRE" }, 
    { "WOODE", "MAN-S" }, 
    "wooden barrel", 
    { Bits::ovison, Bits::vehbit, Bits::openbit, Bits::burnbit } ,
    obj_funcs::barrel(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a man-sized barrel here which you might be able to enter."), OP(ObjectSlots::ksl_ocapac, 100), OP(ObjectSlots::ksl_osize, 70) }},
{{ "BALLO", "BASKE" }, 
    { "WICKE" }, 
    "basket", 
    { Bits::ovison, Bits::vehbit, Bits::openbit } ,
    obj_funcs::balloon(), 
    { "CBAG", 
      "BROPE", 
      "RECEP"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is a very large and extremely heavy wicker basket with a cloth\nbag here. Inside the basket is a metal receptacle of some kind. \nAttached to the basket on the outside is a piece of wire."), OP(ObjectSlots::ksl_ocapac, 100), OP(ObjectSlots::ksl_osize, 70), OP(ObjectSlots::ksl_ovtype, RoomBit::rairbit) }},
{{ "TBASK", "CAGE", "DUMBW", "BASKE" }, 
    {  }, 
    "basket", 
    { Bits::ovison, Bits::transbit, Bits::contbit, Bits::openbit } ,
    obj_funcs::dumbwaiter(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "At the end of the chain is a basket."), OP(ObjectSlots::ksl_ocapac, 50) }},
{{ "BAT", "VAMPI" }, 
    { "VAMPI" }, 
    "bat", 
    { Bits::ovison, Bits::ndescbit, Bits::trytakebit } ,
    obj_funcs::fly_me()},
{{ "BELL" }, 
    { "SMALL", "BRASS" }, 
    "bell", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "Lying in a corner of the room is a small brass bell."), OP(ObjectSlots::ksl_odesc1, "There is a small brass bell here.") }},
{{ "HBELL", "BELL" }, 
    { "BRASS", "HOT", "RED" }, 
    "red hot brass bell", 
    { Bits::ovison, Bits::trytakebit } ,
    obj_funcs::hbell_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "On the ground is a red hot bell.") }},
{{ "BLWAL", "WALL", "PANEL" }, 
    { "BLACK" }, 
    "black panel", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::mpanels()},
{{ "AXE" }, 
    { "BLOOD" }, 
    "bloody axe", 
    { Bits::ovison, Bits::weaponbit } ,
    obj_funcs::axe_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a bloody axe here."), OP(ObjectSlots::ksl_osize, 25) }},
{{ "BLBK", "BOOK" }, 
    { "BLUE" }, 
    "blue book", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::contbit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a blue book here."), OP(ObjectSlots::ksl_ocapac, 2), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_oread, greek_to_me) }},
{{ "BLABE", "LABEL" }, 
    { "BLUE" }, 
    "blue label", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a blue label here."), OP(ObjectSlots::ksl_osize, 1), OP(ObjectSlots::ksl_oread, "\n	  !!!!  FROBOZZ MAGIC BALLOON COMPANY !!!!\n\nHello, Aviator!\n\nInstructions for use:\n   \n   To get into balloon, say 'Board'\n   To leave balloon, say 'Disembark'\n   To land, say 'Land'\n    \nWarranty:\n   \n   No warranty is expressed or implied.  You're on your own, sport!\n\n					Good Luck.\n") }},
{{ "BOLT", "BOLT", "NUT" }, 
    { "METAL" }, 
    "bolt", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit, Bits::turnbit } ,
    obj_funcs::bolt_function()},
{{ "BOOK", "PRAYE", "BIBLE", "GOODB" }, 
    { "LARGE", "BLACK" }, 
    "book", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::contbit, Bits::burnbit } ,
    obj_funcs::black_book(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "On the altar is a large black book, open to page 569."), OP(ObjectSlots::ksl_odesc1, "There is a large black book here."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_oread, "		COMMANDMENT #12592\nOh ye who go about saying unto each:   \"Hello sailor\":\ndost thou know the magnitude of thy sin before the gods?\nYea, verily, thou shalt be ground between two stones.\nShall the angry gods cast thy body into the whirlpool?\nSurely, thy eye shall be put out with a sharp stick!\nEven unto the ends of the earth shalt thou wander and\nunto the land of the dead shalt thou be sent at last.\nSurely thou shalt repent of thy cunning.") }},
{{ "SAFE", "BOX" }, 
    { "STEEL" }, 
    "box", 
    { Bits::ovison, Bits::contbit } ,
    obj_funcs::safe_function(), 
    { "CROWN", 
      "CARD"}, 
    { OP(ObjectSlots::ksl_ocapac, 15) }},
{{ "BROPE", "WIRE" }, 
    { "BRAID" }, 
    "braided wire", 
    { Bits::ovison, Bits::tiebit } ,
    obj_funcs::wire_function()},
{{ "BRICK", "BRICK" }, 
    { "SQUAR", "CLAY" }, 
    "brick", 
    { Bits::ovison, Bits::takebit, Bits::burnbit, Bits::searchbit, Bits::openbit } ,
    obj_funcs::brick_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a square brick here which feels like clay."), OP(ObjectSlots::ksl_ocapac, 2), OP(ObjectSlots::ksl_osize, 9) }},
{{ "DBALL", "BALLO", "BASKE" }, 
    { "BROKE" }, 
    "broken balloon", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a balloon here, broken into pieces."), OP(ObjectSlots::ksl_osize, 40) }},
{{ "BLAMP", "LAMP", "LANTE" }, 
    { "BROKE", "BRASS" }, 
    "broken lamp", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a broken brass lantern here.") }},
{{ "STICK" }, 
    { "SHARP", "BROKE" }, 
    "broken sharp stick", 
    { Bits::ovison, Bits::takebit } ,
    obj_funcs::stick_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "A sharp stick, which appears to have been broken at one end, is here."), OP(ObjectSlots::ksl_odesc1, "There is a broken sharp stick here."), OP(ObjectSlots::ksl_osize, 3) }},
{{ "OTIMB", "TIMBE", "PILE" }, 
    { "WOODE", "BROKE" }, 
    "broken timber", 
    { Bits::ovison, Bits::takebit } ,
    obj_funcs::timbers(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, timber_untied), OP(ObjectSlots::ksl_osize, 50) }},
{{ "ODOOR", "DOOR" }, 
    { "BRONZ" }, 
    "bronze door", 
    { Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::bronze_door()},
{{ "SBAG", "BAG", "SACK" }, 
    { "BROWN", "ELONG" }, 
    "brown sack", 
    { Bits::ovison, Bits::takebit, Bits::contbit, Bits::burnbit } ,
    nullptr, 
    { "GARLI", 
      "FOOD"}, 
    { OP(ObjectSlots::ksl_odesco, "On the table is an elongated brown sack, smelling of hot peppers."), OP(ObjectSlots::ksl_odesc1, "A brown sack is here."), OP(ObjectSlots::ksl_ocapac, 15), OP(ObjectSlots::ksl_osize, 3) }},
{{ "BUBBL" }, 
    { "GREEN", "PLAST" }, 
    "green bubble", 
    { Bits::ovison, Bits::ndescbit } },
{{ "COKES", "BOTTL", "BUNCH" }, 
    { "COKE" }, 
    "bunch of Coke bottles", 
    { Bits::ovison, Bits::takebit } ,
    obj_funcs::coke_bottles(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "There is a large pile of empty Coke bottles here, evidently produced\nby the implementers during their long struggle to win totally."), OP(ObjectSlots::ksl_odesc1, "Many empty Coke bottles are here.  Alas, they can't hold water."), OP(ObjectSlots::ksl_osize, 15) }},
{{ "BLANT", "LANTE", "LAMP" }, 
    { "USED", "BURNE", "DEAD", "USELE" }, 
    "burned-out lantern", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "The deceased adventurer's useless lantern is here."), OP(ObjectSlots::ksl_odesc1, "There is a burned-out lantern here."), OP(ObjectSlots::ksl_osize, 20) }},
{{ "YBUTT", "BUTTO", "SWITC" }, 
    { "YELLO" }, 
    "yellow button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::dbuttons()},
{{ "BRBUT", "BUTTO", "SWITC" }, 
    { "BROWN" }, 
    "brown button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::dbuttons()},
{{ "RBUTT", "BUTTO", "SWITC" }, 
    { "RED" }, 
    "red button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::dbuttons()},
{{ "BLBUT", "BUTTO", "SWITC" }, 
    { "BLUE" }, 
    "blue button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::dbuttons()},
{{ "RNBUT", "BUTTO" }, 
    { "ROUND" }, 
    "round button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::buttons()},
{{ "SQBUT", "BUTTO" }, 
    { "SQUAR" }, 
    "square button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::buttons()},
{{ "TRBUT", "BUTTO" }, 
    { "TRIAN" }, 
    "triangular button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::buttons()},
{{ "CARD", "NOTE" }, 
    { "PLAIN" }, 
    "card", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a card with writing on it here."), OP(ObjectSlots::ksl_osize, 1), OP(ObjectSlots::ksl_oread, "\nWarning:\n    This room was constructed over very weak rock strata.  Detonation\nof explosives in this room is strictly prohibited!\n			Frobozz Magic Cave Company\n			per M. Agrippa, foreman\n") }},
{{ "RUG", "CARPE" }, 
    { "ORIEN" }, 
    "carpet", 
    { Bits::ovison, Bits::ndescbit, Bits::trytakebit } ,
    obj_funcs::rug()},
{{ "CDOOR", "DOOR" }, 
    { "WOOD", "WOODE", "CELL" }, 
    "cell door", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::cell_door()},
{{ "CHALI", "CUP", "GOBLE", "SILVE" }, 
    { "SILVE" }, 
    "chalice", 
    { Bits::ovison, Bits::takebit, Bits::contbit } ,
    obj_funcs::chalice(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a silver chalice, intricately engraved, here."), OP(ObjectSlots::ksl_ocapac, 5), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_otval, 10) }},
{{ "CBAG", "BAG" }, 
    { "CLOTH" }, 
    "cloth bag", 
    { Bits::ovison } ,
    obj_funcs::bcontents()},
{{ "GARLI", "CLOVE" }, 
    {  }, 
    "clove of garlic", 
    { Bits::ovison, Bits::takebit, Bits::foodbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a clove of garlic here.") }},
{{ "ARROW", "POINT" }, 
    { "COMPA" }, 
    "compass arrow", 
    { Bits::ovison, Bits::ndescbit } },
{{ "CROWN" }, 
    { "GAUDY" }, 
    "crown", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "The excessively gaudy crown of Lord Dimwit Flathead is here."), OP(ObjectSlots::ksl_odesc1, "Lord Dimwit's crown is here."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 15), OP(ObjectSlots::ksl_otval, 10) }},
{{ "TOMB", "CRYPT", "GRAVE", "TOMB", "DOOR" }, 
    { "MARBL" }, 
    "crypt door", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::crypt_object(), 
    { }, 
    { OP(ObjectSlots::ksl_oread, "Here lie the implementers, whose heads were placed on poles by the\nKeeper of the Dungeon for amazing untastefulness.") }},
{{ "SPHER", "BALL", "PALAN", "STONE" }, 
    { "CRYST", "SEEIN", "GLASS", "WHITE" }, 
    "white crystal sphere", 
    { Bits::ovison, Bits::sacredbit, Bits::trytakebit } ,
    obj_funcs::sphere_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a beautiful white crystal sphere here."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 6), OP(ObjectSlots::ksl_otval, 6) }},
{{ "TRIDE", "FORK" }, 
    { "CRYST" }, 
    "crystal trident", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "On the shore lies Poseidon's own crystal trident."), OP(ObjectSlots::ksl_odesc1, "Poseidon's own crystal trident is here."), OP(ObjectSlots::ksl_osize, 20), OP(ObjectSlots::ksl_ofval, 4), OP(ObjectSlots::ksl_otval, 11) }},
{{ "CYCLO", "ONE-E", "MONST" }, 
    {  }, 
    "cyclops", 
    { Bits::ovison, Bits::vicbit, Bits::villain } ,
    obj_funcs::cyclops(), 
    { }, 
    { OP(ObjectSlots::ksl_ostrength, 10000), OP(ObjectSlots::ksl_ofmsgs, &cyclops_melee) }},
{{ "DAM", "GATE", "GATES", "FCD" }, 
    {  }, 
    "dam", 
    { Bits::ovison, Bits::ndescbit } },
{{ "WDOOR", "DOOR" }, 
    { "WOODE", "WEST", "WESTE" }, 
    "wooden door", 
    { Bits::ovison, Bits::readbit, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::ddoor_function(), 
    { }, 
    { OP(ObjectSlots::ksl_oread, "The engravings translate to 'This space intentionally left blank'") }},
{{ "DOOR", "TRAPD", "TRAP-" }, 
    { "TRAP" }, 
    "trap door", 
    { Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::trap_door()},
{{ "SDOOR", "DOOR" }, 
    { "STONE" }, 
    "stone door", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::ddoor_function()},
{{ "FDOOR", "DOOR" }, 
    { "FRONT" }, 
    "door", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::ddoor_function()},
{{ "STRAD", "VIOLI" }, 
    { "FANCY" }, 
    "fancy violin", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a Stradivarius here."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_otval, 10) }},
{{ "ICE", "MASS", "GLACI" }, 
    {  }, 
    "glacier", 
    { Bits::ovison, Bits::vicbit } ,
    obj_funcs::glacier(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "A mass of ice fills the western half of the room.") }},
{{ "BOTTL", "CONTA" }, 
    { "CLEAR", "GLASS" }, 
    "glass bottle", 
    { Bits::ovison, Bits::takebit, Bits::transbit, Bits::contbit } ,
    obj_funcs::bottle_function(), 
    { "WATER"}, 
    { OP(ObjectSlots::ksl_odesco, "A bottle is sitting on the table."), OP(ObjectSlots::ksl_odesc1, "A clear glass bottle is here."), OP(ObjectSlots::ksl_ocapac, 4) }},
{{ "FLASK" }, 
    { "GLASS" }, 
    "glass flask filled with liquid", 
    { Bits::ovison, Bits::takebit, Bits::transbit } ,
    obj_funcs::flask_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "A stoppered glass flask with a skull-and-crossbones marking is here.\nThe flask is filled with some clear liquid."), OP(ObjectSlots::ksl_ocapac, 5), OP(ObjectSlots::ksl_osize, 10) }},
{{ "COFFI", "CASKE" }, 
    { "GOLD" }, 
    "gold coffin", 
    { Bits::ovison, Bits::takebit, Bits::contbit, Bits::sacredbit } ,
    obj_funcs::timbers(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, coffin_untied), OP(ObjectSlots::ksl_ocapac, 35), OP(ObjectSlots::ksl_osize, 55), OP(ObjectSlots::ksl_ofval, 3), OP(ObjectSlots::ksl_otval, 7) }},
{{ "GRAIL" }, 
    { "HOLY" }, 
    "grail", 
    { Bits::ovison, Bits::takebit, Bits::contbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is an extremely valuable (perhaps original) grail here."), OP(ObjectSlots::ksl_ocapac, 5), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 2), OP(ObjectSlots::ksl_otval, 5) }},
{{ "GRATE", "GRATI" }, 
    {  }, 
    "grating", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::grate_function()},
{{ "GRBK", "BOOK" }, 
    { "GREEN" }, 
    "green book", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::contbit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a green book here."), OP(ObjectSlots::ksl_ocapac, 2), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_oread, greek_to_me) }},
{{ "RBTLB", "PAPER", "PIECE" }, 
    { "GREEN" }, 
    "green piece of paper", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a green piece of paper here."), OP(ObjectSlots::ksl_osize, 3), OP(ObjectSlots::ksl_oread, "	  !!!! 	FROBOZZ MAGIC ROBOT COMPANY  !!!!\n\nHello, Master!\n   \n   I am a late-model robot, trained at MIT Tech to perform various\nsimple household functions. \n\nInstructions for use:\n   To activate me, use the following formula:\n	>TELL ROBOT '<something to do>' <cr>\n   The quotation marks are required!\n       \nWarranty:\n   No warranty is expressed or implied.\n				\n					At your service!\n") }},
{{ "PUMP", "AIR-P", "AIRPU" }, 
    { "SMALL", "HAND-" }, 
    "hand-held air pump", 
    { Bits::ovison, Bits::takebit, Bits::toolbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a small pump here.") }},
{{ "HPOLE", "HEAD" }, 
    {  }, 
    "head on a pole", 
    { Bits::ovison } },
{{ "SSLOT", "SLOT", "HOLE" }, 
    {  }, 
    "hole", 
    { Bits::ovison, Bits::openbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_ocapac, 10) }},
{{ "HOOK2", "HOOK" }, 
    { "SMALL" }, 
    "hook", 
    { Bits::ovison } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, hook_desc) }},
{{ "HOOK1", "HOOK" }, 
    { "SMALL" }, 
    "hook", 
    { Bits::ovison } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, hook_desc) }},
{{ "DIAMO" }, 
    { "HUGE", "ENORM" }, 
    "huge diamond", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is an enormous diamond (perfectly cut) here."), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_otval, 6) }},
{{ "GUANO", "CRAP", "SHIT", "HUNK" }, 
    {  }, 
    "hunk of bat guano", 
    { Bits::ovison, Bits::takebit, Bits::digbit } ,
    obj_funcs::guano_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a hunk of bat guano here."), OP(ObjectSlots::ksl_osize, 20) }},
{{ "JADE", "FIGUR" }, 
    { "JADE" }, 
    "jade figurine", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is an exquisite jade figurine here."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 5), OP(ObjectSlots::ksl_otval, 5) }},
{{ "KNIFE", "BLADE" }, 
    { "NASTY", "UNRUS", "PLAIN" }, 
    "knife", 
    { Bits::ovison, Bits::takebit, Bits::weaponbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "On a table is a nasty-looking knife."), OP(ObjectSlots::ksl_odesc1, "There is a nasty-looking knife lying here."), OP(ObjectSlots::ksl_ofmsgs, &knife_melee) }},
{{ "LAMP", "LANTE", "LIGHT" }, 
    { "BRASS" }, 
    "lamp", 
    { Bits::ovison, Bits::takebit, Bits::lightbit } ,
    obj_funcs::lantern(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "A battery-powered brass lantern is on the trophy case."), OP(ObjectSlots::ksl_odesc1, "There is a brass lantern (battery-powered) here."), OP(ObjectSlots::ksl_osize, 15), OP(ObjectSlots::ksl_olint, olint_t(0, lntin,350)) }},
{{ "DBUTT", "BUTTO" }, 
    { "LARGE" }, 
    "large button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::dialbutton()},
{{ "LCASE", "CASE" }, 
    { "LARGE" }, 
    "large case", 
    { Bits::ovison, Bits::transbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a large case here, containing objects which you used to\npossess.") }},
{{ "EMERA" }, 
    { "LARGE" }, 
    "large emerald", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is an emerald here."), OP(ObjectSlots::ksl_ofval, 5), OP(ObjectSlots::ksl_otval, 10) }},
{{ "ATABL", "TABLE" }, 
    { "LARGE", "OBLON" }, 
    "large oblong table", 
    { Bits::ovison } },
{{ "ADVER", "PAMPH", "LEAFL", "BOOKL", "MAIL" }, 
    { "SMALL" }, 
    "leaflet", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a small leaflet here."), OP(ObjectSlots::ksl_osize, 2), OP(ObjectSlots::ksl_oread, "			WELCOME TO ZORK\n\n    ZORK is a game of adventure, danger, and low cunning.  In it you\nwill explore some of the most amazing territory ever seen by mortal\nman.  Hardened adventurers have run screaming from the terrors\ncontained within!\n\n    In ZORK the intrepid explorer delves into the forgotten secrets\nof a lost labyrinth deep in the bowels of the earth, searching for\nvast treasures long hidden from prying eyes, treasures guarded by\nfearsome monsters and diabolical traps!\n\n    No PDP-10 should be without one!\n\n    ZORK was created at the MIT Laboratory for Computer Science, by\nTim Anderson, Marc Blank, Bruce Daniels, and Dave Lebling.  It was\ninspired by the ADVENTURE game of Crowther and Woods, and the long\ntradition of fantasy and science fiction adventure.  ZORK is written\nin MDL (alias MUDDLE).\n\n    On-line information may be available using the HELP and INFO\ncommands (most systems).\n\n    Direct inquiries, comments, etc. by Net mail to ZORK@MIT-DMS.\n\n    (c) Copyright 1978,1979 Massachusetts Institute of Technology.  \n		       All rights reserved.\n\n    This version was ported to C++ from the original MDL sources by\nJeff Claar, who apparently does not have better things to do with \nhis time. However, it is still maintained (albeit sporadically) so\npull requests or bug reports are encouraged if any problems are found.\n\nIssues can be reported at https://bitbucket.org/jclaar3/zork/issues.\n") }},
{{ "*BUN*" }, 
    {  }, 
    "", 
    { Bits::ovison, Bits::bunchbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_obverb, nullptr) }},
{{ "LEAK", "DRIP", "HOLE" }, 
    {  }, 
    "leak", 
    { Bits::ndescbit } ,
    obj_funcs::leak_function()},
{{ "MDOOR", "DOOR" }, 
    { "LOCKE", "WOOD", "WOODE", "CELL" }, 
    "locked door", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::locked_door()},
{{ "LDOOR", "DOOR" }, 
    { "LOCKE", "WOOD", "WOODE", "CELL" }, 
    "locked door", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::locked_door()},
{{ "LPOLE", "POLE", "POST" }, 
    { "LONG", "CENTE" }, 
    "long pole", 
    { Bits::ovison, Bits::ndescbit } },
{{ "MACHI", "PDP10", "DRYER", "LID" }, 
    {  }, 
    "machine", 
    { Bits::ovison, Bits::contbit } ,
    obj_funcs::machine_function(), 
    { }, 
    { OP(ObjectSlots::ksl_ocapac, 50) }},
{{ "RBOAT", "BOAT" }, 
    { "MAGIC", "PLAST", "SEAWO" }, 
    "magic boat", 
    { Bits::ovison, Bits::takebit, Bits::burnbit, Bits::vehbit, Bits::openbit } ,
    obj_funcs::rboat_function(), 
    { "LABEL"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is an inflated boat here."), OP(ObjectSlots::ksl_ocapac, 100), OP(ObjectSlots::ksl_osize, 20), OP(ObjectSlots::ksl_ovtype, RoomBit::rwaterbit) }},
{{ "OAKND", "WALL", "PANEL" }, 
    { "MAHOG" }, 
    "mahogany wall", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::mends()},
{{ "MAILB", "BOX" }, 
    { "SMALL" }, 
    "mailbox", 
    { Bits::ovison, Bits::contbit } ,
    nullptr, 
    { "ADVER"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is a small mailbox here."), OP(ObjectSlots::ksl_ocapac, 10) }},
{{ "CAGE" }, 
    { "MANGL", "STEEL" }, 
    "steel cage", 
    { Bits::ovison, Bits::ndescbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a mangled steel cage here."), OP(ObjectSlots::ksl_osize, 60) }},
{{ "MATCH", "FLINT" }, 
    {  }, 
    "matchbook", 
    { Bits::ovison, Bits::readbit, Bits::takebit } ,
    obj_funcs::match_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a matchbook whose cover says 'Visit Beautiful FCD#3' here."), OP(ObjectSlots::ksl_osize, 2), OP(ObjectSlots::ksl_omatch, 5), OP(ObjectSlots::ksl_oread, "	        [close cover before striking BKD]\n\n	YOU too can make BIG MONEY in the exciting field of\n		      PAPER SHUFFLING!\n\nMr. TAA of Muddle, Mass. says: \"Before I took this course I used\nto be a lowly bit twiddler.  Now with what I learned at MIT Tech\nI feel really important and can obfuscate and confuse with the best.\"\n\nMr. MARC had this to say: \"Ten short days ago all I could look\nforward to was a dead-end job as a doctor.  Now I have a promising\nfuture and make really big Zorkmids.\"\n\nMIT Tech can't promise these fantastic results to everyone.  But when\nyou earn your MDL degree from MIT Tech your future will be brighter.\n\n	      Send for our free brochure today.") }},
{{ "REFL2", "MIRRO" }, 
    {  }, 
    "mirror", 
    { Bits::ovison, Bits::vicbit, Bits::trytakebit } ,
    obj_funcs::mirror_mirror()},
{{ "REFL1", "MIRRO" }, 
    {  }, 
    "mirror", 
    { Bits::ovison, Bits::vicbit, Bits::trytakebit } ,
    obj_funcs::mirror_mirror()},
{{ "PAPER", "NEWSP", "ISSUE", "REPOR", "MAGAZ", "NEWS" }, 
    {  }, 
    "newspaper", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is an issue of US NEWS & DUNGEON REPORT dated 12/01/17 here."), OP(ObjectSlots::ksl_osize, 2), OP(ObjectSlots::ksl_oread, "		US NEWS & DUNGEON REPORT\n12/01/17  				       Last G.U.E. Edition\n\nThis version of ZORK is no longer being supported on this or any other\nmachine.  In particular, bugs and feature requests will, most likely, be\nread and ignored.  There are updated versions of ZORK, including some\naltogether new problems, available for PDP-11s and various\nmicrocomputers (TRS-80, APPLE, maybe more later).  For information, send\na SASE to:\n\n                Infocom, Inc.\n                P.O. Box 120, Kendall Station\n                Cambridge, Ma. 02142\n\nJust kidding.  Please don't send anything to this address.  This PO box\ncould now be used by a plumbing supply company, a dropbox for Russian\nspies, a cover for a bank VP's mistress, or any number of other things.\nWhat it is most certainly NOT used for is a location to get more information\nabout Infocom products.  Search the internet for all of them.  If you really\nwant more information about something, perhaps you should send for a \nbrochure?  It might be worth a point or two...\n") }},
{{ "EIGHT", "8" }, 
    {  }, 
    "number eight", 
    { Bits::ovison, Bits::ndescbit } },
{{ "FIVE", "5" }, 
    {  }, 
    "number five", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::take_five()},
{{ "FOUR", "4" }, 
    {  }, 
    "number four", 
    { Bits::ovison, Bits::ndescbit } },
{{ "ONE", "1" }, 
    {  }, 
    "number one", 
    { Bits::ovison, Bits::ndescbit } },
{{ "SEVEN", "7" }, 
    {  }, 
    "number seven", 
    { Bits::ovison, Bits::ndescbit } },
{{ "SIX", "6" }, 
    {  }, 
    "number six", 
    { Bits::ovison, Bits::ndescbit } },
{{ "THREE", "3" }, 
    {  }, 
    "number three", 
    { Bits::ovison, Bits::ndescbit } },
{{ "TWO", "2" }, 
    {  }, 
    "number two", 
    { Bits::ovison, Bits::ndescbit } },
{{ "PAINT", "ART", "CANVA", "MASTE", "PICTU", "WORK" }, 
    {  }, 
    "painting", 
    { Bits::ovison, Bits::takebit, Bits::burnbit } ,
    obj_funcs::painting(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "Fortunately, there is still one chance for you to be a vandal, for on\nthe far wall is a work of unparalleled beauty."), OP(ObjectSlots::ksl_odesc1, "A masterpiece by a neglected genius is here."), OP(ObjectSlots::ksl_osize, 15), OP(ObjectSlots::ksl_ofval, 4), OP(ObjectSlots::ksl_otval, 7) }},
{{ "CANDL", "PAIR" }, 
    {  }, 
    "pair of candles", 
    { Bits::ovison, Bits::takebit, Bits::lightbit, Bits::flamebit, Bits::onbit } ,
    obj_funcs::candles(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "On the two ends of the altar are burning candles."), OP(ObjectSlots::ksl_odesc1, "There are two candles here."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_olint, olint_t(0, cndin,50)) }},
{{ "PEARL", "NECKL" }, 
    { "PEARL" }, 
    "pearl necklace", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a pearl necklace here with hundreds of large pearls."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 9), OP(ObjectSlots::ksl_otval, 5) }},
{{ "ECAKE", "CAKE" }, 
    { "EATME", "EAT-M" }, 
    "piece of 'Eat-Me' cake", 
    { Bits::ovison, Bits::takebit, Bits::foodbit } ,
    obj_funcs::eatme_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a piece of cake here with the words 'Eat-Me' on it."), OP(ObjectSlots::ksl_osize, 10) }},
{{ "BLICE", "CAKE", "ICING" }, 
    { "BLUE", "ECCH" }, 
    "piece of cake with blue icing", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::foodbit } ,
    obj_funcs::cake_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a piece of cake with blue (ecch) icing here."), OP(ObjectSlots::ksl_osize, 4) }},
{{ "ORICE", "CAKE", "ICING" }, 
    { "ORANG" }, 
    "piece of cake with orange icing", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::foodbit } ,
    obj_funcs::cake_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a piece of cake with orange icing here."), OP(ObjectSlots::ksl_osize, 4) }},
{{ "RDICE", "CAKE", "ICING" }, 
    { "RED" }, 
    "piece of cake with red icing", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::foodbit } ,
    obj_funcs::cake_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a piece of cake with red icing here."), OP(ObjectSlots::ksl_osize, 4) }},
{{ "GUNK", "PIECE", "SLAG" }, 
    { "VITRE" }, 
    "piece of vitreous slag", 
    { Bits::ovison, Bits::takebit, Bits::trytakebit } ,
    obj_funcs::gunk_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a small piece of vitreous slag here."), OP(ObjectSlots::ksl_osize, 10) }},
{{ "BODIE", "BODY", "CORPS", "PILE" }, 
    {  }, 
    "pile of bodies", 
    { Bits::ovison, Bits::ndescbit, Bits::trytakebit } ,
    obj_funcs::body_function()},
{{ "CORPS", "PILE" }, 
    { "MANGL" }, 
    "pile of corpses", 
    { Bits::ovison } },
{{ "LEAVE", "LEAF", "PILE" }, 
    {  }, 
    "pile of leaves", 
    { Bits::ovison, Bits::takebit, Bits::burnbit } ,
    obj_funcs::leaf_pile(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a pile of leaves on the ground."), OP(ObjectSlots::ksl_osize, 25) }},
{{ "PINND", "WALL", "PANEL", "DOOR" }, 
    { "PINE" }, 
    "pine wall", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::mends()},
{{ "DBOAT", "BOAT", "PILE", "PLAST" }, 
    { "PLAST" }, 
    "plastic boat (with hole)", 
    { Bits::ovison, Bits::takebit, Bits::burnbit } ,
    obj_funcs::dboat_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a pile of plastic here with a large hole in it."), OP(ObjectSlots::ksl_osize, 20) }},
{{ "IBOAT", "BOAT", "PILE", "PLAST" }, 
    { "PLAST" }, 
    "pile of plastic", 
    { Bits::ovison, Bits::takebit, Bits::burnbit } ,
    obj_funcs::iboat_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a folded pile of plastic here which has a small valve\nattached."), OP(ObjectSlots::ksl_osize, 20) }},
{{ "BAR", "PLATI" }, 
    { "PLATI", "LARGE" }, 
    "platinum bar", 
    { Bits::ovison, Bits::takebit, Bits::sacredbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a large platinum bar here."), OP(ObjectSlots::ksl_osize, 20), OP(ObjectSlots::ksl_ofval, 12), OP(ObjectSlots::ksl_otval, 10) }},
{{ "PLEAK", "LEAK" }, 
    { "LARGE" }, 
    "leak", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::pleak()},
{{ "POOL", "SEWAG", "GOOP" }, 
    { "LARGE", "BROWN" }, 
    "pool of sewage", 
    { Bits::ovison, Bits::vicbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "The leak has submerged the depressed area in a pool of sewage.") }},
{{ "POT", "GOLD" }, 
    { "GOLD" }, 
    "pot of gold", 
    { Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "At the end of the rainbow is a pot of gold."), OP(ObjectSlots::ksl_odesc1, "There is a pot of gold here."), OP(ObjectSlots::ksl_osize, 15), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_otval, 10) }},
{{ "PRAYE", "INSCR" }, 
    { "ANCIE", "OLD" }, 
    "prayer", 
    { Bits::ovison, Bits::readbit, Bits::sacredbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_oread, "The prayer is inscribed in an ancient script which is hardly\nremembered these days, much less understood.  What little of it can\nbe made out seems to be a philippic against small insects,\nabsent-mindedness, and the picking up and dropping of small objects. \nThe final verse seems to consign trespassers to the land of the\ndead.  All evidence indicates that the beliefs of the ancient\nZorkers were obscure.") }},
{{ "COIN", "ZORKM", "GOLD" }, 
    { "GOLD", "PRICE" }, 
    "priceless zorkmid", 
    { Bits::ovison, Bits::readbit, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "On the floor is a gold zorkmid coin (a valuable collector's item)."), OP(ObjectSlots::ksl_odesc1, "There is an engraved zorkmid coin here."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_otval, 12), OP(ObjectSlots::ksl_oread, "\n	       --------------------------\n	      /      Gold Zorkmid	 \\\n	     /  T e n   T h o u s a n d   \\\n	    /        Z O R K M I D S	   \\\n	   /				    \\\n	  /        ||||||||||||||||||	     \\\n	 /        !||||		 ||||!	      \\\n	|	   |||   ^^  ^^   |||	       |\n	|	   |||	 OO  OO   |||	       |\n	| In Frobs  |||	   <<    |||  We Trust |\n	|	     || (______) ||	       |\n	|	      |          |	       |\n	|	      |__________|	       |\n	 \\				      /\n	  \\    -- Lord Dimwit Flathead --    /\n	   \\    -- Beloved of Zorkers --    /\n	    \\				   /\n	     \\	     * 722 G.U.E. *       /\n	      \\				 /\n	       --------------------------\n") }},
{{ "PUBK", "BOOK" }, 
    { "PURPL" }, 
    "purple book", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::contbit, Bits::burnbit } ,
    nullptr, 
    { "STAMP"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is a purple book here."), OP(ObjectSlots::ksl_ocapac, 2), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_oread, greek_to_me) }},
{{ "WATER", "QUANT", "LIQUI", "H2O" }, 
    {  }, 
    "quantity of water", 
    { Bits::ovison, Bits::takebit, Bits::drinkbit } ,
    obj_funcs::water_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is some water here"), OP(ObjectSlots::ksl_osize, 4) }},
{{ "RAILI", "RAIL" }, 
    { "WOODE" }, 
    "wooden railing", 
    { Bits::ovison, Bits::ndescbit } },
{{ "RAINB" }, 
    {  }, 
    "rainbow", 
    { Bits::ovison, Bits::ndescbit } },
{{ "RECEP" }, 
    { "METAL" }, 
    "receptacle", 
    { Bits::ovison, Bits::contbit, Bits::searchbit } ,
    obj_funcs::bcontents(), 
    { }, 
    { OP(ObjectSlots::ksl_ocapac, 6) }},
{{ "RBEAM", "BEAM", "LIGHT" }, 
    { "RED" }, 
    "red beam of light", 
    { Bits::ovison, Bits::ndescbit, Bits::openbit } ,
    obj_funcs::beam_function(), 
    { }, 
    { OP(ObjectSlots::ksl_ocapac, 1000) }},
{{ "BUOY" }, 
    { "RED" }, 
    "red buoy", 
    { Bits::ovison, Bits::takebit, Bits::contbit, Bits::findmebit } ,
    nullptr, 
    { "EMERA"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is a red buoy here (probably a warning)."), OP(ObjectSlots::ksl_ocapac, 20), OP(ObjectSlots::ksl_osize, 10) }},
{{ "RSWIT", "SWITC", "BUTTO" }, 
    { "RED" }, 
    "red button", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::mrswitch()},
{{ "RDWAL", "WALL", "PANEL" }, 
    { "RED" }, 
    "red panel", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::mpanels()},
{{ "ROBOT", "R2D2", "C3PO", "ROBBY" }, 
    {  }, 
    "robot", 
    { Bits::ovison, Bits::vicbit, Bits::sacredbit, Bits::actorbit } ,
    obj_funcs::robot_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a robot here."), OP(ObjectSlots::ksl_oactor, e_oactor::robot) }},
{{ "ROPE", "HEMP", "COIL" }, 
    { "LARGE" }, 
    "rope", 
    { Bits::ovison, Bits::takebit, Bits::tiebit, Bits::sacredbit } ,
    obj_funcs::rope_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "A large coil of rope is lying in the corner."), OP(ObjectSlots::ksl_odesc1, "There is a large coil of rope here."), OP(ObjectSlots::ksl_osize, 10) }},
{{ "RUBY" }, 
    { "MOBY" }, 
    "ruby", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "On the floor lies a moby ruby."), OP(ObjectSlots::ksl_odesc1, "There is a moby ruby lying here."), OP(ObjectSlots::ksl_ofval, 15), OP(ObjectSlots::ksl_otval, 8) }},
{{ "RKNIF", "KNIFE" }, 
    { "RUSTY" }, 
    "rusty knife", 
    { Bits::ovison, Bits::takebit, Bits::weaponbit } ,
    obj_funcs::rusty_knife(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "Beside the skeleton is a rusty knife."), OP(ObjectSlots::ksl_odesc1, "There is a rusty knife here."), OP(ObjectSlots::ksl_osize, 20), OP(ObjectSlots::ksl_ofmsgs, &knife_melee) }},
{{ "SAND", "BEACH" }, 
    { "SANDY" }, 
    "sandy beach", 
    { Bits::ovison, Bits::digbit } ,
    obj_funcs::sand_function()},
{{ "BRACE", "JEWEL", "SAPPH" }, 
    { "SAPPH" }, 
    "sapphire bracelet", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a sapphire-encrusted bracelet here."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_ofval, 5), OP(ObjectSlots::ksl_otval, 3) }},
{{ "SCREW" }, 
    {  }, 
    "screwdriver", 
    { Bits::ovison, Bits::takebit, Bits::toolbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a screwdriver here.") }},
{{ "HEADS", "HEAD", "POLE", "POLES", "PDL", "BKD", "TAA", "MARC", "IMPLE", "LOSER" }, 
    {  }, 
    "set of poled heads", 
    { Bits::ovison, Bits::sacredbit, Bits::trytakebit } ,
    obj_funcs::head_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There are four heads here, mounted securely on poles.") }},
{{ "KEYS", "SET", "KEY" }, 
    {  }, 
    "set of skeleton keys", 
    { Bits::ovison, Bits::takebit, Bits::toolbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a set of skeleton keys here."), OP(ObjectSlots::ksl_osize, 10) }},
{{ "SPOLE", "POLE", "POST", "HANDG", "GRIP" }, 
    { "SHORT", "SMALL" }, 
    "short pole", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::short_pole()},
{{ "SHOVE" }, 
    { "LARGE" }, 
    "shovel", 
    { Bits::ovison, Bits::takebit, Bits::toolbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a large shovel here."), OP(ObjectSlots::ksl_osize, 15) }},
{{ "BONES", "SKELE", "BODY" }, 
    {  }, 
    "skeleton", 
    { Bits::ovison, Bits::trytakebit } ,
    obj_funcs::skeleton(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "A skeleton, probably the remains of a luckless adventurer, lies here.") }},
{{ "COAL", "PILE", "HEAP" }, 
    { "SMALL" }, 
    "small pile of coal", 
    { Bits::ovison, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a small heap of coal here."), OP(ObjectSlots::ksl_osize, 20) }},
{{ "LISTS", "PAPER", "LIST", "PRINT", "LISTI", "STACK", "OUTPU" }, 
    { "GIGAN", "LINE-" }, 
    "stack of listings", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "There is a gigantic pile of line-printer output here.  Although the\npaper once contained useful information, almost nothing can be\ndistinguished now."), OP(ObjectSlots::ksl_odesc1, "There is an enormous stack of line-printer paper here.  It is barely\nreadable."), OP(ObjectSlots::ksl_osize, 70), OP(ObjectSlots::ksl_oread, "<DEFINE FEEL-FREE (LOSER)\n		   <TELL \"FEEL FREE, CHOMPER!\">>\n			...\nThe rest is, alas, unintelligible (as were the implementers).") }},
{{ "STAMP" }, 
    { "FLATH" }, 
    "Flathead stamp", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a Flathead stamp here."), OP(ObjectSlots::ksl_osize, 1), OP(ObjectSlots::ksl_ofval, 4), OP(ObjectSlots::ksl_otval, 10), OP(ObjectSlots::ksl_oread, "\n---v----v----v----v----v----v----v----v---\n|					 |\n|	   ||||||||||	     LORD	 |\n>         !||||	     |	    DIMWIT	 <\n|	  ||||    ---|	   FLATHEAD	 |\n|	  |||C	   CC \\  		 |\n>	   ||||	      _\\		 <\n|	    ||| (____|			 |\n|	     ||      |			 |\n>	      |______|	     Our	 <\n|		/   \\	  Excessive	 |\n|	       /     \\	    Leader	 |\n>	      |	      |			 <\n|	      |       |			 |\n|					 |\n>    G.U.E. POSTAGE	   3 Zorkmids    <\n|					 |\n---^----^----^----^----^----^----^----^---\n") }},
{{ "STATU", "SCULP", "ROCK" }, 
    { "BEAUT" }, 
    "statue", 
    { Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a beautiful statue here."), OP(ObjectSlots::ksl_osize, 8), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_otval, 13) }},
{{ "IRBOX", "BOX" }, 
    { "STEEL", "DENTE" }, 
    "steel box", 
    { Bits::takebit, Bits::contbit } ,
    nullptr, 
    { "STRAD"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is a dented steel box here."), OP(ObjectSlots::ksl_ocapac, 20), OP(ObjectSlots::ksl_osize, 40) }},
{{ "RCAGE", "CAGE" }, 
    { "STEEL" }, 
    "steel cage", 
    { Bits::ovison } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a steel cage in the middle of the room.") }},
{{ "STILL" }, 
    { "VICIO" }, 
    "stiletto", 
    { Bits::ovison, Bits::weaponbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a vicious-looking stiletto here."), OP(ObjectSlots::ksl_osize, 10) }},
{{ "DIAL", "SUNDI" }, 
    { "SUN" }, 
    "sundial", 
    { Bits::ovison, Bits::ndescbit, Bits::turnbit } ,
    obj_funcs::dial()},
{{ "MSWIT", "SWITC" }, 
    {  }, 
    "switch", 
    { Bits::ovison, Bits::ndescbit, Bits::turnbit } ,
    obj_funcs::mswitch_function()},
{{ "SWORD", "ORCRI", "GLAMD", "BLADE" }, 
    { "ELVIS" }, 
    "sword", 
    { Bits::ovison, Bits::takebit, Bits::weaponbit } ,
    obj_funcs::sword(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "On hooks above the mantelpiece hangs an elvish sword of great\nantiquity."), OP(ObjectSlots::ksl_odesc1, "There is an elvish sword here."), OP(ObjectSlots::ksl_osize, 30), OP(ObjectSlots::ksl_ofmsgs, &sword_melee), OP(ObjectSlots::ksl_otval, 0) }},
{{ "LABEL", "FINEP", "PRINT" }, 
    { "TAN", "FINE" }, 
    "tan label", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a tan label here."), OP(ObjectSlots::ksl_osize, 2), OP(ObjectSlots::ksl_oread, "	  !!!! 	FROBOZZ MAGIC BOAT COMPANY  !!!!\n\nHello, Sailor!\n\nInstructions for use:\n   \n   To get into boat, say 'Board'\n   To leave boat, say 'Disembark'\n\n   To get into a body of water, say 'Launch'\n   To get to shore, say 'Land'\n    \nWarranty:\n\n  This boat is guaranteed against all defects in parts and\nworkmanship for a period of 76 milliseconds from date of purchase or\nuntil first used, whichever comes first.\n\nWarning:\n   This boat is made of plastic.		Good Luck!\n") }},
{{ "THIEF", "ROBBE", "CROOK", "CRIMI", "BANDI", "GENT", "GENTL", "MAN", "INDIV" }, 
    { "SHADY", "SUSPI" }, 
    "thief", 
    { Bits::ovison, Bits::vicbit, Bits::villain } ,
    obj_funcs::robber_function(), 
    { "STILL"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is a suspicious-looking individual, holding a bag, leaning\nagainst one wall.  He is armed with a vicious-looking stiletto."), OP(ObjectSlots::ksl_ostrength, 5), OP(ObjectSlots::ksl_ofmsgs, &thief_melee) }},
{{ "SAFFR", "TIN", "SPICE" }, 
    { "RARE" }, 
    "tin of spices", 
    { Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a tin of rare spices here."), OP(ObjectSlots::ksl_osize, 8), OP(ObjectSlots::ksl_ofval, 5), OP(ObjectSlots::ksl_otval, 5) }},
{{ "TORCH", "IVORY" }, 
    { "IVORY" }, 
    "torch", 
    { Bits::ovison, Bits::takebit, Bits::lightbit, Bits::flamebit, Bits::toolbit, Bits::onbit } ,
    obj_funcs::torch_object(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "Sitting on the pedestal is a flaming torch, made of ivory."), OP(ObjectSlots::ksl_odesc1, "There is an ivory torch here."), OP(ObjectSlots::ksl_osize, 20), OP(ObjectSlots::ksl_ofval, 14), OP(ObjectSlots::ksl_otval, 6) }},
{{ "GUIDE", "BOOK" }, 
    { "TOUR" }, 
    "tour guidebook", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "Some guidebooks entitled 'Flood Control Dam #3' are on the reception\ndesk."), OP(ObjectSlots::ksl_odesc1, "There are tour guidebooks here."), OP(ObjectSlots::ksl_oread, "\"		   Guide Book to\n		Flood Control Dam #3\n\n  Flood Control Dam #3 (FCD#3) was constructed in year 783 of the\nGreat Underground Empire to harness the destructive power of the\nFrigid River.  This work was supported by a grant of 37 million\nzorkmids from the Central Bureaucracy and your omnipotent local\ntyrant Lord Dimwit Flathead the Excessive. This impressive\nstructure is composed of 3.7 cubic feet of concrete, is 256 feet\ntall at the center, and 193 feet wide at the top.  The reservoir\ncreated behind the dam has a volume of 37 billion cubic feet, an\narea of 12 million square feet, and a shore line of 36 thousand\nfeet.\n\n  The construction of FCD#3 took 112 days from ground breaking to\nthe dedication. It required a work force of 384 slaves, 34 slave\ndrivers, 12 engineers, 2 turtle doves, and a partridge in a pear\ntree. The work was managed by a command team composed of 2345\nbureaucrats, 2347 secretaries (at least two of whom can type),\n12,256 paper shufflers, 52,469 rubber stampers, 245,193 red tape\nprocessors, and nearly one million dead trees.\n\n  We will now point out some of the more interesting features\nof FCD#3 as we conduct you on a guided tour of the facilities:\n	1) You start your tour here in the Dam Lobby.\n	   You will notice on your right that .........") }},
{{ "TROLL" }, 
    { "NASTY" }, 
    "troll", 
    { Bits::ovison, Bits::vicbit, Bits::villain } ,
    obj_funcs::troll(), 
    { "AXE"}, 
    { OP(ObjectSlots::ksl_odesc1, "A nasty-looking troll, brandishing a bloody axe, blocks all passages\nout of the room."), OP(ObjectSlots::ksl_ostrength, 2), OP(ObjectSlots::ksl_ofmsgs, &troll_melee) }},
{{ "TCASE", "CASE" }, 
    { "TROPH" }, 
    "trophy case", 
    { Bits::ovison, Bits::transbit, Bits::contbit } ,
    obj_funcs::trophy_case(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a trophy case here."), OP(ObjectSlots::ksl_ocapac, bigfix) }},
{{ "TRUNK", "CHEST", "JEWEL" }, 
    { "OLD" }, 
    "trunk of jewels", 
    { Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "Lying half buried in the mud is an old trunk, bulging with jewels."), OP(ObjectSlots::ksl_odesc1, "There is an old trunk here, bulging with assorted jewels."), OP(ObjectSlots::ksl_osize, 35), OP(ObjectSlots::ksl_ofval, 15), OP(ObjectSlots::ksl_otval, 8) }},
{{ "TUBE", "TOOTH" }, 
    {  }, 
    "tube", 
    { Bits::ovison, Bits::takebit, Bits::contbit, Bits::readbit } ,
    obj_funcs::tube_function(), 
    { "PUTTY"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is an object which looks like a tube of toothpaste here."), OP(ObjectSlots::ksl_ocapac, 7), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_oread, "---> Frobozz Magic Gunk Company <---\n	  All-Purpose Gunk") }},
{{ "PUTTY", "MATER", "GUNK", "GLUE" }, 
    { "VISCO" }, 
    "viscous material", 
    { Bits::ovison, Bits::takebit, Bits::toolbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is some gunk here"), OP(ObjectSlots::ksl_osize, 6) }},
{{ "ENGRA", "INSCR" }, 
    { "OLD", "ANCIE" }, 
    "wall with engravings", 
    { Bits::ovison, Bits::readbit, Bits::sacredbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There are old engravings on the walls here."), OP(ObjectSlots::ksl_oread, "The engravings were incised in the living rock of the cave wall by\nan unknown hand.  They depict, in symbolic form, the beliefs of the\nancient peoples of Zork.  Skillfully interwoven with the bas reliefs\nare excerpts illustrating the major tenets expounded by the sacred\ntexts of the religion of that time.  Unfortunately a later age seems\nto have considered them blasphemous and just as skillfully excised\nthem.") }},
{{ "ETCH2", "ETCHI", "WALLS", "WALL" }, 
    {  }, 
    "wall with etchings", 
    { Bits::ovison, Bits::readbit, Bits::ndescbit, Bits::findmebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_oread, "		        o  b  o\n		    r 		  z\n		 f   M  A  G  I  C   z\n		 c    W  E   L  L    y\n		    o		  n\n		        m  p  a\n") }},
{{ "ETCH1", "ETCHI", "WALLS", "WALL" }, 
    {  }, 
    "wall with etchings", 
    { Bits::ovison, Bits::readbit, Bits::ndescbit, Bits::findmebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_oread, "		        o  b  o\n\n		        A  G  I\n		         E   L\n\n		        m  p  a\n") }},
{{ "TTREE", "TREE" }, 
    { "LARGE" }, 
    "large tree", 
    { Bits::ovison, Bits::ndescbit, Bits::climbbit } },
{{ "FTREE", "TREE" }, 
    { "LARGE" }, 
    "large tree", 
    { Bits::ovison, Bits::ndescbit, Bits::climbbit } },
{{ "CCLIF", "CLIFF", "LEDGE" }, 
    { "ROCKY", "SHEER" }, 
    "cliff", 
    { Bits::ovison, Bits::ndescbit, Bits::climbbit } },
{{ "WCLIF", "CLIFF" }, 
    { "WHITE" }, 
    "white cliffs", 
    { Bits::ovison, Bits::ndescbit, Bits::climbbit } ,
    obj_funcs::wclif_object()},
{{ "WHBK", "BOOK" }, 
    { "WHITE" }, 
    "white book", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::contbit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a white book here."), OP(ObjectSlots::ksl_ocapac, 2), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_oread, greek_to_me) }},
{{ "WHWAL", "WALL", "PANEL" }, 
    { "WHITE" }, 
    "white panel", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::mpanels()},
{{ "WINDO" }, 
    {  }, 
    "window", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::window_function()},
{{ "FUSE", "COIL", "WIRE" }, 
    { "SHINY", "THIN" }, 
    "wire coil", 
    { Bits::ovison, Bits::takebit, Bits::burnbit } ,
    obj_funcs::fuse_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a coil of thin shiny wire here."), OP(ObjectSlots::ksl_osize, 1), OP(ObjectSlots::ksl_olint, olint_t(0, fusin,2)) }},
{{ "WDBAR", "BAR" }, 
    { "WOOD", "WOODE", "CROSS" }, 
    "wooden bar", 
    { Bits::ovison, Bits::ndescbit } },
{{ "BUCKE" }, 
    { "WOODE" }, 
    "wooden bucket", 
    { Bits::ovison, Bits::vehbit, Bits::openbit } ,
    obj_funcs::bucket(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a wooden bucket here, 3 feet in diameter and 3 feet high."), OP(ObjectSlots::ksl_ocapac, 100), OP(ObjectSlots::ksl_osize, 100), OP(ObjectSlots::ksl_ovtype, RoomBit::rbuckbit) }},
{{ "QDOOR", "DOOR" }, 
    { "WOOD", "WOODE" }, 
    "wooden door", 
    { Bits::ovison, Bits::doorbit, Bits::ndescbit } ,
    obj_funcs::wood_door()},
{{ "POSTS", "POST" }, 
    { "WOODE" }, 
    "group of wooden posts", 
    { Bits::ovison } },
{{ "WRENC" }, 
    {  }, 
    "wrench", 
    { Bits::ovison, Bits::takebit, Bits::toolbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a wrench here."), OP(ObjectSlots::ksl_osize, 10) }},
{{ "YLWAL", "WALL", "PANEL" }, 
    { "YELLO" }, 
    "yellow panel", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::mpanels()},
{{ "TCHST", "CHEST" }, 
    { "TOOL" }, 
    "group of tool chests", 
    { Bits::ovison, Bits::ndescbit } ,
    obj_funcs::tool_chest()},
{{ "CPANL", "PANEL" }, 
    { "CONTR" }, 
    "control panel", 
    { Bits::ovison, Bits::ndescbit } },
{{ "BROCH" }, 
    { "FREE" }, 
    "free brochure", 
    { Bits::ovison, Bits::takebit, Bits::burnbit, Bits::contbit, Bits::openbit, Bits::readbit } ,
    obj_funcs::brochure(), 
    { "DSTMP"}, 
    { OP(ObjectSlots::ksl_odesco, "In the mailbox is a large brochure."), OP(ObjectSlots::ksl_odesc1, "There is a large brochure here."), OP(ObjectSlots::ksl_osize, 30), OP(ObjectSlots::ksl_ocapac, 1) }},
{{ "DSTMP", "STAMP" }, 
    { "DON", "WOODS", "DWOOD" }, 
    "Don Woods stamp", 
    { Bits::ovison, Bits::takebit, Bits::burnbit, Bits::readbit } ,
    obj_funcs::brochure(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a Don Woods Commemorative stamp here."), OP(ObjectSlots::ksl_osize, 1), OP(ObjectSlots::ksl_otval, 1), OP(ObjectSlots::ksl_oread, "\n---v----v----v----v----v---\n|	  _______	  |\n>  One	 /  	 \\     G  <\n| Lousy /   	  \\    U  |\n> Point	|   ___   |    E  <\n|	|  (___)  |	  |\n>	<--)___(-->    P  <\n|	/ /	\\ \\    o  |\n>      / /	 \\ \\   s  <\n|     |-|---------|-|  t  |\n>     | |  \\ _ /  | |  a  <\n|     | | --(_)-- | |  g  |\n>     | |  /| |\\  | |  e  <\n|     |-|---|_|---|-|	  |\n>      \\ \\__/_\\__/ /	  <\n|	_/_______\\_	  |\n>      |  f.m.l.c. |	  <\n|      -------------	  |\n>			  <\n|   Donald Woods, Editor  |\n>     Spelunker Today	  <\n|			  |\n---^----^----^----^----^---") }},
{{ "BILLS", "STACK", "PILE" }, 
    { "NEAT", "200", "ZORKM" }, 
    "stack of zorkmid bills", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    obj_funcs::bills_object(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "200 neatly stacked zorkmid bills are here."), OP(ObjectSlots::ksl_odesco, "On the floor sit 200 neatly stacked zorkmid bills."), OP(ObjectSlots::ksl_osize, 10), OP(ObjectSlots::ksl_otval, 15), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_oread, "\n______________________________________________________________\n| 1  0   0          GREAT UNDERGROUND EMPIRE         1  0   0 |\n| 1 0 0 0 0					     1 0 0 0 0|\n| 1 0 0 0 0					     1 0 0 0 0|\n| 1  0   0		    DIMWIT		     1  0   0 |\n|	               ||||||||||||||||	  		      |\n|		       ||   __  __   ||		   B30332744D |\n|		       ||  -OO  OO-  ||	  		      |\n|	IN  FROBS      \\||    >>    ||/	    WE  TRUST         |\n|		        ||  ______  ||	       		      |\n| B30332744D	         |  ------  |	       		      |\n|                        \\\\________//	       		      |\n| 1  0   0    Series	   FLATHEAD	LD Flathead  1  0   0 |\n| 1 0 0 0 0   719GUE	   		 Treasurer   1 0 0 0 0|\n| 1 0 0 0 0 					     1 0 0 0 0|\n| 1  0   0	  One Hundred Royal Zorkmids	     1  0   0 |\n|_____________________________________________________________|\n\n") }},
{{ "PORTR", "PAINT", "ART" }, 
    { "FLATH" }, 
    "portrait of J. Pierpont Flathead", 
    { Bits::ovison, Bits::readbit, Bits::takebit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "The portrait of J. Pierpont Flathead is here."), OP(ObjectSlots::ksl_odesco, "A portrait of J. Pierpont Flathead hangs on the wall."), OP(ObjectSlots::ksl_osize, 25), OP(ObjectSlots::ksl_otval, 5), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_oread, " 		    \n	             ||||||||||||||\n		    ||   __  __   ||\n		    ||	 $$  $$   ||\n		    \\||	   >>    ||/\n		     ||  ______  ||	       \n		      |  -//--   |	       \n		      \\\\_//_____//	       \n	 	     ___//|  |	\n		    /__// |  |\n			  |  |\n	       __________//  \\\\__________\n	      / $ /	  ****	     \\ $ \\\n	     /   /	   **	      \\   \\\n	    /	/|	   **	      |\\   \\\n	   /   / |	   **	      | \\   \\\n	  /   /  |         **         |  \\   \\\n	  ^   ^__|______$Z$**$Z$______|___^   ^\n	  \\   	    *	$Z$**$Z$   *	     /\n	   \\________*___$Z$**$Z$___*________/\n		 |	$Z$**$Z$      |\n\n 	 	 J.  PIERPONT  FLATHEAD\n			CHAIRMAN\n") }},
{{ "VAULT", "CUBE", "LETTE" }, 
    { "STONE", "LARGE" }, 
    "large stone cube", 
    { Bits::ovison, Bits::readbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_oread, "	        Bank of Zork\n		   VAULT\n         	 *722 GUE*\n          Frobozz Magic Vault Company\n") }},
{{ "SCOL", "CURTA", "LIGHT" }, 
    { "SHIMM" }, 
    "shimmering curtain of light", 
    { Bits::ovison} ,
    obj_funcs::scol_object()},
{{ "ZGNOM", "GNOME" }, 
    { "ZURIC" }, 
    "Gnome of Zurich", 
    { Bits::ovison, Bits::vicbit, Bits::villain } ,
    obj_funcs::zgnome_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a Gnome of Zurich here.") }},
{{ "NEST" }, 
    { "BIRDS", "SMALL" }, 
    "birds nest", 
    { Bits::ovison, Bits::takebit, Bits::burnbit, Bits::openbit } ,
    nullptr, 
    { "EGG"}, 
    { OP(ObjectSlots::ksl_odesc1, "There is a small birds nest here."), OP(ObjectSlots::ksl_odesco, "On the branch is a small birds nest."), OP(ObjectSlots::ksl_ocapac, 20) }},
{{ "EGG" }, 
    { "BIRDS", "ENCRU" }, 
    "jewel-encrusted egg", 
    { Bits::ovison, Bits::takebit, Bits::contbit } ,
    obj_funcs::egg_object(), 
    { "GCANA"}, 
    { OP(ObjectSlots::ksl_ofval, 5), OP(ObjectSlots::ksl_otval, 5), OP(ObjectSlots::ksl_odesc1, "There is a jewel-encrusted egg here."), OP(ObjectSlots::ksl_ocapac, 6), OP(ObjectSlots::ksl_odesco, "In the bird's nest is a large egg encrusted with precious jewels,\napparently scavenged somewhere by a childless songbird.  The egg is \ncovered with fine gold inlay, and ornamented in lapis lazuli and\nmother-of-pearl.  Unlike most eggs, this one is hinged and has a\ndelicate looking clasp holding it closed.  The egg appears extremely\nfragile.") }},
{{ "BEGG", "EGG" }, 
    { "BROKE", "BIRDS", "ENCRU" }, 
    "broken jewel-encrusted egg", 
    { Bits::ovison, Bits::takebit, Bits::contbit, Bits::openbit } ,
    nullptr, 
    { "BCANA"}, 
    { OP(ObjectSlots::ksl_ocapac, 6), OP(ObjectSlots::ksl_odesc1, "There is a somewhat ruined egg here.") }},
{{ "BAUBL" }, 
    { "BRASS", "BEAUT" }, 
    "beautiful brass bauble", 
    { Bits::ovison, Bits::takebit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_ofval, 1), OP(ObjectSlots::ksl_otval, 1), OP(ObjectSlots::ksl_odesc1, "There is a beautiful brass bauble here.") }},
{{ "GCANA", "CANAR" }, 
    { "CLOCK", "MECHA", "GOLD", "GOLDE" }, 
    "clockwork canary", 
    { Bits::ovison, Bits::takebit } ,
    obj_funcs::canary_object(), 
    { }, 
    { OP(ObjectSlots::ksl_ofval, 6), OP(ObjectSlots::ksl_otval, 2), OP(ObjectSlots::ksl_odesc1, "There is golden clockwork canary here."), OP(ObjectSlots::ksl_odesco, "There is a golden clockwork canary nestled in the egg.  It has ruby\neyes and a silver beak.  Through a crystal window below its left\nwing you can see intricate machinery inside.  It appears to have\nwound down.") }},
{{ "BCANA", "CANAR" }, 
    { "BROKE", "CLOCK", "MECHA", "GOLD", "GOLDE" }, 
    "broken clockwork canary", 
    { Bits::ovison, Bits::takebit } ,
    obj_funcs::canary_object(), 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a non-functional canary here."), OP(ObjectSlots::ksl_odesco, "There is a golden clockwork canary nestled in the egg.  It seems to\nhave recently had a bad experience.  The mountings for its jewel-like\neyes are empty, and its silver beak is crumpled.  Through a cracked\ncrystal window below its left wing you can see the remains of\nintricate machinery.  It is not clear what result winding it would\nhave, as the mainspring seems sprung.") }},
{{ "WARNI", "NOTE", "PAPER", "PIECE" }, 
    {  }, 
    "note of warning", 
    { Bits::ovison, Bits::takebit, Bits::readbit, Bits::burnbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a piece of paper on the ground here."), OP(ObjectSlots::ksl_oread, "\nThe paper is rather worn; although the writing is barely legible (the\nauthor probably had only a used pencil), it is a very elegant\ncopperplate.\n \nTo Whom It May Concern:\n\n     I regret to report that the rumours regarding treasure contained\nin the chamber to which this passage leads have no basis in fact.\nShould you nevertheless be sufficiently foolhardy to enter, it will\nbe quite impossible for you to exit.\n				\n				Sincerely yours,\n				The Thief\n") }},
{{ "CPSLT", "SLIT", "SLOT" }, 
    { "SMALL" }, 
    "small slit", 
    { Bits::ovison, Bits::ndescbit, Bits::openbit } ,
    obj_funcs::cpslt_object(), 
    { }, 
    { OP(ObjectSlots::ksl_ocapac, 4) }},
{{ "CPDR2", "DOOR" }, 
    { "STEEL" }, 
    "steel door", 
    { Bits::ovison, Bits::ndescbit } },
{{ "CPDOR", "DOOR" }, 
    { "STEEL" }, 
    "steel door", 
    { Bits::ovison, Bits::ndescbit } },
{{ "GCARD", "CARD" }, 
    { "GOLD" }, 
    "gold card", 
    { Bits::takebit, Bits::ovison, Bits::readbit } ,
    nullptr, 
    { }, 
    { OP(ObjectSlots::ksl_odesc1, "There is a solid gold engraved card here."), OP(ObjectSlots::ksl_odesco, "Nestled inside the niche is an engraved gold card."), OP(ObjectSlots::ksl_oread, "\n ____________________________________________________________\n|							     |\n|              FROBOZZ MAGIC SECURITY SYSTEMS		     |\n|    Door Pass                  Royal Zork Puzzle Museum     |\n|							     |\n|                     #632-988-496-XTHF			     |\n|							     |\n|							     |\n|     USE OF THIS PASS BY UNAUTHORIZED PERSONS OR AFTER	     |\n|   EXPIRATION DATE WILL RESULT IN IMMEDIATE CONFISCATION    |\n|							     |\n|							     |\n|                              (approved)		     |\n|                              Will Weng		     |\n|                               789 G.U.E.		     |\n|							     |\n|                                        Expires 792 G.U.E.  |\n|____________________________________________________________|\n"), OP(ObjectSlots::ksl_otval, 15), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_osize, 4) }},
{{ "PDOOR", "DOOR" }, 
    { "WOODE", "OAK" }, 
    "door made of oak", 
    { Bits::ovison, Bits::doorbit, Bits::contbit } ,
    obj_funcs::pdoor_function()},
{{ "PWIND", "WINDO" }, 
    { "BARRE" }, 
    "barred window", 
    { Bits::ovison, Bits::doorbit } ,
    obj_funcs::pwind_function()},
{{ "PLID1", "LID" }, 
    { "METAL" }, 
    "metal lid", 
    { Bits::ovison, Bits::ndescbit, Bits::contbit } ,
    obj_funcs::plid_function()},
{{ "PLID2", "LID" }, 
    { "METAL" }, 
    "metal lid", 
    { Bits::ovison, Bits::ndescbit, Bits::contbit, Bits::openbit } ,
    obj_funcs::plid_function()},
{{ "PTABL", "TABLE" }, 
    { "DUSTY", "WOODE" }, 
    "table", 
    { Bits::ovison, Bits::ndescbit } },
{{ "PCRAK", "CRACK" }, 
    { "NARRO" }, 
    "narrow crack", 
    { Bits::ovison, Bits::ndescbit } },
{{ "PKH1", "KEYHO", "HOLE" }, 
    {  }, 
    "keyhole", 
    { Bits::ovison, Bits::ndescbit, Bits::openbit } ,
    obj_funcs::pkh_function(), 
    { }, 
    { OP(ObjectSlots::ksl_ocapac, 12) }},
{{ "PKH2", "KEYHO", "HOLE" }, 
    {  }, 
    "keyhole", 
    { Bits::ovison, Bits::ndescbit, Bits::openbit } ,
    obj_funcs::pkh_function(), 
    { "PKEY"}, 
    { OP(ObjectSlots::ksl_ocapac, 12) }},
{{ "PKEY", "KEY" }, 
    { "IRON", "RUSTY" }, 
    "rusty iron key", 
    { Bits::ovison, Bits::takebit, Bits::ndescbit, Bits::turnbit, Bits::toolbit } ,
    obj_funcs::pkey_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, ""), OP(ObjectSlots::ksl_odesc1, "There is a rusty iron key here.") }},
{{ "PALAN", "STONE", "SPHER" }, 
    { "GLASS", "SEEIN", "CRYST", "BLUE" }, 
    "blue crystal sphere", 
    { Bits::ovison, Bits::takebit } ,
    obj_funcs::palantir(), 
    { }, 
    { OP(ObjectSlots::ksl_otval, 5), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_odesco, "In the center of the table sits a blue crystal sphere."), OP(ObjectSlots::ksl_odesc1, "There is blue crystal sphere here.") }},
{{ "MAT" }, 
    { "WELCO", "RUBBE" }, 
    "welcome mat", 
    { Bits::ovison, Bits::takebit, Bits::readbit } ,
    obj_funcs::mat_function(), 
    { }, 
    { OP(ObjectSlots::ksl_odesco, "A rubber mat saying 'Welcome to Zork!' lies by the door."), OP(ObjectSlots::ksl_odesc1, "There is a welcome mat here."), OP(ObjectSlots::ksl_oread, "Welcome to Zork!"), OP(ObjectSlots::ksl_osize, 12) }},
{{ "STOVE" }, 
    { "OLD" }, 
    "old coal stove", 
    { Bits::ovison, Bits::ndescbit, Bits::flamebit, Bits::onbit } ,
    obj_funcs::stove_function()},
{{ "PAL3", "PALAN", "STONE", "SPHER" }, 
    { "GLASS", "SEEIN", "CRYST", "RED" }, 
    "red crystal sphere", 
    { Bits::ovison, Bits::takebit } ,
    obj_funcs::palantir(), 
    { }, 
    { OP(ObjectSlots::ksl_otval, 5), OP(ObjectSlots::ksl_ofval, 10), OP(ObjectSlots::ksl_odesco, "On the floor sits a red crystal sphere."), OP(ObjectSlots::ksl_odesc1, "There is red crystal sphere here.") }},
};
