mr(R"~(WHOUS)~", 
    R"~(This is an open field west of a white house, with a boarded front door.)~", 
    R"~(West of House)~", 
    { Ex(direction::North, R"~(NHOUS)~"), Ex(direction::South, R"~(SHOUS)~"), Ex(direction::West, R"~(FORE1)~"), Ex(direction::East, NExit(R"~(The door is locked, and there is evidently no key.)~")) }, 
    { "FDOOR", 
      "MAILB", 
      "MAT"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::housebit })) }),
mr(R"~(NHOUS)~", 
    R"~(You are facing the north side of a white house.  There is no door here,
and all the windows are barred.)~", 
    R"~(North of House)~", 
    { Ex(direction::West, R"~(WHOUS)~"), Ex(direction::East, R"~(EHOUS)~"), Ex(direction::North, R"~(FORE3)~"), Ex(direction::South, NExit(R"~(The windows are all barred.)~")) }, 
    { }, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::dwindow, Bits::housebit })) }),
mr(R"~(SHOUS)~", 
    R"~(You are facing the south side of a white house. There is no door here,
and all the windows are barred.)~", 
    R"~(South of House)~", 
    { Ex(direction::West, R"~(WHOUS)~"), Ex(direction::East, R"~(EHOUS)~"), Ex(direction::South, R"~(FORE2)~"), Ex(direction::North, NExit(R"~(The windows are all barred.)~")) }, 
    { }, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::dwindow, Bits::housebit })) }),
mr(R"~(EHOUS)~", 
    R"~()~", 
    R"~(Behind House)~", 
    { Ex(direction::North, R"~(NHOUS)~"), Ex(direction::South, R"~(SHOUS)~"), Ex(direction::East, R"~(CLEAR)~"), Ex(direction::West, kitchen_window_EHOUS), Ex(direction::Enter, kitchen_window_EHOUS) }, 
    { "WINDO"}, 
    room_funcs::east_house(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::housebit })) }),
mr(R"~(KITCH)~", 
    R"~()~", 
    R"~(Kitchen)~", 
    { Ex(direction::East, kitchen_window_KITCH), Ex(direction::West, R"~(LROOM)~"), Ex(direction::Exit, kitchen_window_KITCH), Ex(direction::Up, R"~(ATTIC)~"), Ex(direction::Down, NExit(R"~(Only Santa Claus climbs down chimneys.)~")) }, 
    { "WINDO", 
      "SBAG", 
      "BOTTL"}, 
    room_funcs::kitchen(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rhousebit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rval, 10) }),
mr(R"~(ATTIC)~", 
    R"~(This is the attic.  The only exit is stairs that lead down.)~", 
    R"~(Attic)~", 
    { Ex(direction::Down, R"~(KITCH)~") }, 
    { "BRICK", 
      "ROPE", 
      "KNIFE"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rhousebit } ),
mr(R"~(LROOM)~", 
    R"~()~", 
    R"~(Living Room)~", 
    { Ex(direction::East, R"~(KITCH)~"), Ex(direction::West, std::make_shared<CExit>(FlagId::magic_flag, "BLROO", "The door is nailed shut.")), Ex(direction::Down, std::make_shared<DoorExit>(R"~(DOOR)~", R"~(LROOM)~", R"~(CELLA)~")) }, 
    { "WDOOR", 
      "DOOR", 
      "TCASE", 
      "LAMP", 
      "RUG", 
      "PAPER", 
      "SWORD"}, 
    room_funcs::living_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rhousebit, RoomBit::rsacredbit } ),
mr(R"~(FORE1)~", 
    stfore, 
    forest, 
    { Ex(direction::Up, notree_FORE1), Ex(direction::North, R"~(FORE1)~"), Ex(direction::East, R"~(FORE3)~"), Ex(direction::South, R"~(FORE2)~"), Ex(direction::West, R"~(FORE1)~") }, 
    { }, 
    room_funcs::forest_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::treebit, Bits::birdbit, Bits::housebit })) }),
mr(R"~(FORE2)~", 
    fordes, 
    forest, 
    { Ex(direction::Up, notree_FORE2), Ex(direction::North, R"~(SHOUS)~"), Ex(direction::East, R"~(CLEAR)~"), Ex(direction::South, R"~(FORE4)~"), Ex(direction::West, R"~(FORE1)~") }, 
    { }, 
    room_funcs::forest_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::treebit, Bits::birdbit, Bits::housebit })) }),
mr(R"~(FORE3)~", 
    fortree, 
    forest, 
    { Ex(direction::Up, R"~(TREE)~"), Ex(direction::North, R"~(FORE2)~"), Ex(direction::East, R"~(CLEAR)~"), Ex(direction::South, R"~(CLEAR)~"), Ex(direction::West, R"~(NHOUS)~") }, 
    { "FTREE"}, 
    room_funcs::forest_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::birdbit, Bits::housebit })) }),
mr(R"~(TREE)~", 
    R"~()~", 
    R"~(Up a Tree)~", 
    { Ex(direction::Down, R"~(FORE3)~"), Ex(direction::Up, NExit(R"~(You cannot climb any higher.)~")) }, 
    { "NEST", 
      "TTREE"}, 
    room_funcs::tree_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::birdbit, Bits::housebit })) }),
mr(R"~(FORE4)~", 
    R"~(This is a large forest, with trees obstructing all views except
to the east, where a small clearing may be seen through the trees.)~", 
    forest, 
    { Ex(direction::Up, notree_FORE4), Ex(direction::East, R"~(CLTOP)~"), Ex(direction::North, R"~(FORE5)~"), Ex(direction::South, R"~(FORE4)~"), Ex(direction::West, R"~(FORE2)~") }, 
    { }, 
    room_funcs::forest_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::treebit, Bits::birdbit, Bits::housebit })) }),
mr(R"~(FORE5)~", 
    stfore, 
    forest, 
    { Ex(direction::Up, notree_FORE5), Ex(direction::North, R"~(FORE5)~"), Ex(direction::Se, R"~(CLTOP)~"), Ex(direction::South, R"~(FORE4)~"), Ex(direction::West, R"~(FORE2)~") }, 
    { }, 
    room_funcs::forest_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::treebit, Bits::birdbit, Bits::housebit })) }),
mr(R"~(CLEAR)~", 
    R"~()~", 
    R"~(Clearing)~", 
    { Ex(direction::Sw, R"~(EHOUS)~"), Ex(direction::Se, R"~(FORE5)~"), Ex(direction::North, R"~(CLEAR)~"), Ex(direction::East, R"~(CLEAR)~"), Ex(direction::West, R"~(FORE3)~"), Ex(direction::South, R"~(FORE2)~"), Ex(direction::Down, std::make_shared<DoorExit>(R"~(GRATE)~", R"~(MGRAT)~", R"~(CLEAR)~", R"~(You can't go through the closed grating.)~")) }, 
    { "GRATE", 
      "LEAVE"}, 
    room_funcs::clearing(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::housebit })) }),
mr(R"~(CELLA)~", 
    R"~()~", 
    R"~(Cellar)~", 
    { Ex(direction::East, R"~(MTROL)~"), Ex(direction::South, R"~(CHAS2)~"), Ex(direction::Up, std::make_shared<DoorExit>(R"~(DOOR)~", R"~(LROOM)~", R"~(CELLA)~")), Ex(direction::West, NExit(R"~(You try to ascend the ramp, but it is impossible, and you slide back down.)~")) }, 
    { "DOOR"}, 
    room_funcs::cellar(), 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rval, 25) }),
mr(R"~(MTROL)~", 
    R"~(This is a small room with passages off in all directions. 
Bloodstains and deep scratches (perhaps made by an axe) mar the
walls.)~", 
    R"~(The Troll Room)~", 
    { Ex(direction::West, R"~(CELLA)~"), Ex(direction::East, std::make_shared<CExit>(FlagId::troll_flag, "CRAW4", tchomp)), Ex(direction::North, std::make_shared<CExit>(FlagId::troll_flag, "PASS1", tchomp)), Ex(direction::South, std::make_shared<CExit>(FlagId::troll_flag, "MAZE1", tchomp)) }, 
    { "TROLL"}),
mr(R"~(STUDI)~", 
    R"~(This is what appears to have been an artist's studio.  The walls
and floors are splattered with paints of 69 different colors. 
Strangely enough, nothing of value is hanging here.  At the north and
northwest of the room are open doors (also covered with paint).  An
extremely dark and narrow chimney leads up from a fireplace; although
you might be able to get up it, it seems unlikely you could get back
down.)~", 
    R"~(Studio)~", 
    { Ex(direction::North, R"~(CRAW4)~"), Ex(direction::Nw, R"~(GALLE)~"), Ex(direction::Up, std::make_shared<CExit>(FlagId::light_load, "KITCH", "The chimney is too narrow for you and all of your baggage.", false, exit_funcs::chimney_function())) }, 
    { }),
mr(R"~(GALLE)~", 
    R"~(This is an art gallery.  Most of the paintings which were here
have been stolen by vandals with exceptional taste.  The vandals
left through either the north, south, or west exits.)~", 
    R"~(Gallery)~", 
    { Ex(direction::North, R"~(CHAS2)~"), Ex(direction::South, R"~(STUDI)~"), Ex(direction::West, R"~(BKENT)~") }, 
    { "PAINT"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(MAZE1)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::West, R"~(MTROL)~"), Ex(direction::North, R"~(MAZE1)~"), Ex(direction::South, R"~(MAZE2)~"), Ex(direction::East, R"~(MAZE4)~") }, 
    { }),
mr(R"~(MAZE2)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::South, R"~(MAZE1)~"), Ex(direction::North, R"~(MAZE4)~"), Ex(direction::East, R"~(MAZE3)~") }, 
    { }),
mr(R"~(MAZE3)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::West, R"~(MAZE2)~"), Ex(direction::North, R"~(MAZE4)~"), Ex(direction::Up, R"~(MAZE5)~") }, 
    { }),
mr(R"~(MAZE4)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::West, R"~(MAZE3)~"), Ex(direction::North, R"~(MAZE1)~"), Ex(direction::East, R"~(DEAD1)~") }, 
    { }),
mr(R"~(DEAD1)~", 
    deadend, 
    sdeadend, 
    { Ex(direction::South, R"~(MAZE4)~") }, 
    { }),
mr(R"~(MAZE5)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::East, R"~(DEAD2)~"), Ex(direction::North, R"~(MAZE3)~"), Ex(direction::Sw, R"~(MAZE6)~") }, 
    { "BONES", 
      "BAGCO", 
      "KEYS", 
      "BLANT", 
      "RKNIF"}),
mr(R"~(DEAD2)~", 
    deadend, 
    sdeadend, 
    { Ex(direction::West, R"~(MAZE5)~") }, 
    { }),
mr(R"~(MAZE6)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::Down, R"~(MAZE5)~"), Ex(direction::East, R"~(MAZE7)~"), Ex(direction::West, R"~(MAZE6)~"), Ex(direction::Up, R"~(MAZE9)~") }, 
    { }),
mr(R"~(MAZE7)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::Up, R"~(MAZ14)~"), Ex(direction::West, R"~(MAZE6)~"), Ex(direction::Ne, R"~(DEAD1)~"), Ex(direction::East, R"~(MAZE8)~"), Ex(direction::South, R"~(MAZ15)~") }, 
    { }),
mr(R"~(MAZE8)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::Ne, R"~(MAZE7)~"), Ex(direction::West, R"~(MAZE8)~"), Ex(direction::Se, R"~(DEAD3)~") }, 
    { }),
mr(R"~(DEAD3)~", 
    deadend, 
    deadend, 
    { Ex(direction::North, R"~(MAZE8)~") }, 
    { }),
mr(R"~(MAZE9)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::North, R"~(MAZE6)~"), Ex(direction::East, R"~(MAZ11)~"), Ex(direction::Down, R"~(MAZ10)~"), Ex(direction::South, R"~(MAZ13)~"), Ex(direction::West, R"~(MAZ12)~"), Ex(direction::Nw, R"~(MAZE9)~") }, 
    { }),
mr(R"~(MAZ10)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::East, R"~(MAZE9)~"), Ex(direction::West, R"~(MAZ13)~"), Ex(direction::Up, R"~(MAZ11)~") }, 
    { }),
mr(R"~(MAZ11)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::Ne, R"~(MGRAT)~"), Ex(direction::Down, R"~(MAZ10)~"), Ex(direction::Nw, R"~(MAZ13)~"), Ex(direction::Sw, R"~(MAZ12)~") }, 
    { }),
mr(R"~(MGRAT)~", 
    R"~()~", 
    R"~(Grating Room)~", 
    { Ex(direction::Sw, R"~(MAZ11)~"), Ex(direction::Up, std::make_shared<DoorExit>(R"~(GRATE)~", R"~(MGRAT)~", R"~(CLEAR)~", R"~(The grating is locked.)~")) }, 
    { "GRATE"}, 
    room_funcs::maze_11()),
mr(R"~(MAZ12)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::West, R"~(MAZE5)~"), Ex(direction::Sw, R"~(MAZ11)~"), Ex(direction::East, R"~(MAZ13)~"), Ex(direction::Up, R"~(MAZE9)~"), Ex(direction::North, R"~(DEAD4)~") }, 
    { }),
mr(R"~(DEAD4)~", 
    deadend, 
    deadend, 
    { Ex(direction::South, R"~(MAZ12)~") }, 
    { }),
mr(R"~(MAZ13)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::East, R"~(MAZE9)~"), Ex(direction::Down, R"~(MAZ12)~"), Ex(direction::South, R"~(MAZ10)~"), Ex(direction::West, R"~(MAZ11)~") }, 
    { }),
mr(R"~(MAZ14)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::West, R"~(MAZ15)~"), Ex(direction::Nw, R"~(MAZ14)~"), Ex(direction::Ne, R"~(MAZE7)~"), Ex(direction::South, R"~(MAZE7)~") }, 
    { }),
mr(R"~(MAZ15)~", 
    mazedesc, 
    smazedesc, 
    { Ex(direction::West, R"~(MAZ14)~"), Ex(direction::South, R"~(MAZE7)~"), Ex(direction::Ne, R"~(CYCLO)~") }, 
    { }),
mr(R"~(CYCLO)~", 
    R"~()~", 
    R"~(Cyclops Room)~", 
    { Ex(direction::West, R"~(MAZ15)~"), Ex(direction::North, std::make_shared<CExit>(FlagId::magic_flag, "BLROO", "The north wall is solid rock.")), Ex(direction::Up, std::make_shared<CExit>(FlagId::cyclops_flag, "TREAS", "The cyclops doesn't look like he'll let you past.")) }, 
    { "CYCLO"}, 
    room_funcs::cyclops_room()),
mr(R"~(BLROO)~", 
    R"~(This is a long passage.  To the south is one entrance.  On the
east there is an old wooden door, with a large hole in it (about
cyclops sized).)~", 
    R"~(Strange Passage)~", 
    { Ex(direction::South, R"~(CYCLO)~"), Ex(direction::East, R"~(LROOM)~") }, 
    { }, 
    room_funcs::time(), 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rval, 10) }),
mr(R"~(TREAS)~", 
    R"~(This is a large room, whose north wall is solid granite.  A number
of discarded bags, which crumble at your touch, are scattered about
on the floor.  There is an exit down and what appears to be a newly
created passage to the east.)~", 
    R"~(Treasure Room)~", 
    { Ex(direction::Down, R"~(CYCLO)~"), Ex(direction::East, R"~(CPANT)~") }, 
    { "CHALI"}, 
    room_funcs::treasure_room(), 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rval, 25) }),
mr(R"~(RAVI1)~", 
    R"~(This is a deep ravine at a crossing with an east-west crawlway. 
Some stone steps are at the south of the ravine and a steep staircase
descends.)~", 
    R"~(Deep Ravine)~", 
    { Ex(direction::South, R"~(PASS1)~"), Ex(direction::Down, std::make_shared<CExit>(FlagId::egypt_flag, "RESES", "The stairs are to steep for you with your burden.", true, exit_funcs::coffin_cure())), Ex(direction::East, R"~(CHAS1)~"), Ex(direction::West, R"~(CRAW1)~") }, 
    { }),
mr(R"~(CRAW1)~", 
    R"~(This is a crawlway with a three-foot high ceiling.  Your footing
is very unsure here due to the assortment of rocks underfoot. 
Passages can be seen in the east, west, and northwest corners of the
passage.)~", 
    R"~(Rocky Crawl)~", 
    { Ex(direction::West, R"~(RAVI1)~"), Ex(direction::East, R"~(DOME)~"), Ex(direction::Nw, std::make_shared<CExit>(FlagId::egypt_flag, "EGYPT", "The passage is too narrow to accommodate coffins.", true, exit_funcs::coffin_cure())) }, 
    { }),
mr(R"~(RESES)~", 
    R"~()~", 
    R"~(Reservoir South)~", 
    { Ex(direction::South, std::make_shared<CExit>(FlagId::egypt_flag, "RAVI1", "The coffin will not fit through this passage.", true, exit_funcs::coffin_cure())), Ex(direction::West, R"~(STREA)~"), Ex(direction::Cross, std::make_shared<CExit>(FlagId::low_tide, "RESER", "You are not equipped for swimming.")), Ex(direction::North, std::make_shared<CExit>(FlagId::low_tide, "RESER", "You are not equipped for swimming.")), Ex(direction::Launc, R"~(RESER)~"), Ex(direction::Up, std::make_shared<CExit>(FlagId::egypt_flag, "CANY1", "The stairs are too steep for carrying the coffin.", true, exit_funcs::coffin_cure())) }, 
    { }, 
    room_funcs::reservoir_south(), 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RESER)~", 
    R"~()~", 
    R"~(Reservoir)~", 
    { Ex(direction::North, R"~(RESEN)~"), Ex(direction::South, R"~(RESES)~"), Ex(direction::Up, R"~(INSTR)~"), Ex(direction::Down, NExit(R"~(The dam blocks your way.)~")), Ex(direction::Land, NExit(R"~(You must specify direction.)~")) }, 
    { "TRUNK"}, 
    room_funcs::reservoir(), 
    { RoomBit::rwaterbit, RoomBit::rnwallbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RESEN)~", 
    R"~()~", 
    R"~(Reservoir North)~", 
    { Ex(direction::North, R"~(ATLAN)~"), Ex(direction::Launc, R"~(RESER)~"), Ex(direction::Cross, std::make_shared<CExit>(FlagId::low_tide, "RESER", "You are not equipped for swimming.")), Ex(direction::South, std::make_shared<CExit>(FlagId::low_tide, "RESER", "You are not equipped for swimming.")) }, 
    { "PUMP"}, 
    room_funcs::reservoir_north(), 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(STREA)~", 
    R"~(You are standing on a path beside a gently flowing stream.  The path
travels to the north and the east.)~", 
    R"~(Stream View)~", 
    { Ex(direction::Launc, R"~(INSTR)~"), Ex(direction::East, R"~(RESES)~"), Ex(direction::North, R"~(ICY)~") }, 
    { "FUSE"}, 
    nullptr, 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(INSTR)~", 
    R"~(You are on the gently flowing stream.  The upstream route is too narrow
to navigate and the downstream route is invisible due to twisting
walls.  There is a narrow beach to land on.)~", 
    R"~(Stream)~", 
    { Ex(direction::Up, NExit(R"~(The way is too narrow.)~")), Ex(direction::Land, R"~(STREA)~"), Ex(direction::Down, R"~(RESER)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rwaterbit, RoomBit::rnwallbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(EGYPT)~", 
    R"~(This is a room which looks like an Egyptian tomb.  There is an
ascending staircase in the room as well as doors, east and south.)~", 
    R"~(Egyptian Room)~", 
    { Ex(direction::Up, R"~(ICY)~"), Ex(direction::South, R"~(LEDG3)~"), Ex(direction::East, std::make_shared<CExit>(FlagId::egypt_flag, "CRAW1", "The passage is too narrow to accommodate coffins.", true, exit_funcs::coffin_cure())) }, 
    { "COFFI"}),
mr(R"~(ICY)~", 
    R"~()~", 
    R"~(Glacier Room)~", 
    { Ex(direction::North, R"~(STREA)~"), Ex(direction::East, R"~(EGYPT)~"), Ex(direction::West, std::make_shared<CExit>(FlagId::glacier_flag, "RUBYR", "")) }, 
    { "ICE"}, 
    room_funcs::glacier_room()),
mr(R"~(RUBYR)~", 
    R"~(This is a small chamber behind the remains of the Great Glacier.
To the south and west are small passageways.)~", 
    R"~(Ruby Room)~", 
    { Ex(direction::West, R"~(LAVA)~"), Ex(direction::South, R"~(ICY)~") }, 
    { "RUBY"}),
mr(R"~(ATLAN)~", 
    R"~(This is an ancient room, long under water.  There are exits here
to the southeast and upward.)~", 
    R"~(Atlantis Room)~", 
    { Ex(direction::Se, R"~(RESEN)~"), Ex(direction::Up, R"~(CAVE1)~") }, 
    { "TRIDE"}),
mr(R"~(CANY1)~", 
    R"~(You are on the south edge of a deep canyon.  Passages lead off
to the east, south, and northwest.  You can hear the sound of
flowing water below.)~", 
    R"~(Deep Canyon)~", 
    { Ex(direction::Nw, std::make_shared<CExit>(FlagId::egypt_flag, "RESES", "The passage is too steep for carrying the coffin.", true, exit_funcs::coffin_cure())), Ex(direction::East, R"~(DAM)~"), Ex(direction::South, R"~(CAROU)~") }, 
    { }),
mr(R"~(ECHO)~", 
    R"~(This is a large room with a ceiling which cannot be detected from
the ground. There is a narrow passage from east to west and a stone
stairway leading upward.  The room is extremely noisy.  In fact, it is
difficult to hear yourself think.)~", 
    R"~(Loud Room)~", 
    { Ex(direction::East, R"~(CHAS3)~"), Ex(direction::West, R"~(PASS5)~"), Ex(direction::Up, R"~(CAVE3)~") }, 
    { "BAR"}, 
    room_funcs::echo_room()),
mr(R"~(MIRR1)~", 
    R"~()~", 
    R"~(Mirror Room)~", 
    { Ex(direction::West, R"~(PASS3)~"), Ex(direction::North, R"~(CRAW2)~"), Ex(direction::East, R"~(CAVE1)~") }, 
    { "REFL1"}, 
    room_funcs::mirror_room()),
mr(R"~(MIRR2)~", 
    R"~()~", 
    R"~(Mirror Room)~", 
    { Ex(direction::West, R"~(PASS4)~"), Ex(direction::North, R"~(CRAW3)~"), Ex(direction::East, R"~(CAVE2)~") }, 
    { "REFL2"}, 
    room_funcs::mirror_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(CAVE1)~", 
    R"~(This is a small cave with an entrance to the north and a stairway
leading down.)~", 
    R"~(Cave)~", 
    { Ex(direction::North, R"~(MIRR1)~"), Ex(direction::Down, R"~(ATLAN)~") }, 
    { }),
mr(R"~(CAVE2)~", 
    R"~(This is a tiny cave with entrances west and north, and a dark,
forbidding staircase leading down.)~", 
    R"~(Cave)~", 
    { Ex(direction::North, R"~(CRAW3)~"), Ex(direction::West, R"~(MIRR2)~"), Ex(direction::Down, R"~(LLD1)~") }, 
    { }, 
    room_funcs::cave2_room()),
mr(R"~(CRAW2)~", 
    R"~(This is a steep and narrow crawlway.  There are two exits nearby to
the south and southwest.)~", 
    R"~(Steep Crawlway)~", 
    { Ex(direction::South, R"~(MIRR1)~"), Ex(direction::Sw, R"~(PASS3)~") }, 
    { }),
mr(R"~(CRAW3)~", 
    R"~(This is a narrow crawlway.  The crawlway leads from north to south.
However the south passage divides to the south and southwest.)~", 
    R"~(Narrow Crawlway)~", 
    { Ex(direction::South, R"~(CAVE2)~"), Ex(direction::Sw, R"~(MIRR2)~"), Ex(direction::North, R"~(MGRAI)~") }, 
    { }),
mr(R"~(PASS3)~", 
    R"~(This is a cold and damp corridor where a long east-west passageway
intersects with a northward path.)~", 
    R"~(Cold Passage)~", 
    { Ex(direction::East, R"~(MIRR1)~"), Ex(direction::West, R"~(SLIDE)~"), Ex(direction::North, R"~(CRAW2)~") }, 
    { }),
mr(R"~(PASS4)~", 
    R"~(This is a winding passage.  It seems that there is only an exit
on the east end although the whirring from the round room can be
heard faintly to the north.)~", 
    R"~(Winding Passage)~", 
    { Ex(direction::East, R"~(MIRR2)~"), Ex(direction::North, NExit(R"~(You hear the whir from the round room but can find no entrance.)~")) }, 
    { }),
mr(R"~(ENTRA)~", 
    R"~(You are standing at the entrance of what might have been a coal
mine. To the northeast and the northwest are entrances to the mine,
and there is another exit on the south end of the room.)~", 
    R"~(Mine Entrance)~", 
    { Ex(direction::South, R"~(SLIDE)~"), Ex(direction::Nw, R"~(SQUEE)~"), Ex(direction::Ne, R"~(TSHAF)~") }, 
    { }),
mr(R"~(SQUEE)~", 
    R"~(You are a small room.  Strange squeaky sounds may be heard coming from
the passage at the west end.  You may also escape to the south.)~", 
    R"~(Squeaky Room)~", 
    { Ex(direction::West, R"~(BATS)~"), Ex(direction::South, R"~(ENTRA)~") }, 
    { }),
mr(R"~(TSHAF)~", 
    R"~(This is a large room, in the middle of which is a small shaft
descending through the floor into darkness below.  To the west and
the north are exits from this room.  Constructed over the top of the
shaft is a metal framework to which a heavy iron chain is attached.)~", 
    R"~(Shaft Room)~", 
    { Ex(direction::Down, NExit(R"~(You wouldn't fit and would die if you could.)~")), Ex(direction::West, R"~(ENTRA)~"), Ex(direction::North, R"~(TUNNE)~") }, 
    { "TBASK"}),
mr(R"~(TUNNE)~", 
    R"~(This is a narrow tunnel with large wooden beams running across
the ceiling and around the walls.  A path from the south splits into
paths running west and northeast.)~", 
    R"~(Wooden Tunnel)~", 
    { Ex(direction::South, R"~(TSHAF)~"), Ex(direction::West, R"~(SMELL)~"), Ex(direction::Ne, R"~(MINE1)~") }, 
    { }),
mr(R"~(SMELL)~", 
    R"~(This is a small non-descript room.  However, from the direction
of a small descending staircase a foul odor can be detected.  To the
east is a narrow path.)~", 
    R"~(Smelly Room)~", 
    { Ex(direction::Down, R"~(BOOM)~"), Ex(direction::East, R"~(TUNNE)~") }, 
    { }),
mr(R"~(BOOM)~", 
    R"~(This is a small room which smells strongly of coal gas.)~", 
    R"~(Gas Room)~", 
    { Ex(direction::Up, R"~(SMELL)~") }, 
    { "BRACE"}, 
    room_funcs::boom_room(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit } ),
mr(R"~(TLADD)~", 
    R"~(This is a very small room.  In the corner is a rickety wooden
ladder, leading downward.  It might be safe to descend.  There is
also a staircase leading upward.)~", 
    R"~(Ladder Top)~", 
    { Ex(direction::Down, R"~(BLADD)~"), Ex(direction::Up, R"~(MINE7)~") }, 
    { }),
mr(R"~(BLADD)~", 
    R"~(This is a rather wide room.  On one side is the bottom of a
narrow wooden ladder.  To the northeast and the south are passages
leaving the room.)~", 
    R"~(Ladder Bottom)~", 
    { Ex(direction::Ne, R"~(DEAD7)~"), Ex(direction::South, R"~(TIMBE)~"), Ex(direction::Up, R"~(TLADD)~") }, 
    { }),
mr(R"~(DEAD7)~", 
    deadend, 
    deadend, 
    { Ex(direction::South, R"~(BLADD)~") }, 
    { "COAL"}),
mr(R"~(TIMBE)~", 
    R"~(This is a long and narrow passage, which is cluttered with broken
timbers.  A wide passage comes from the north and turns at the 
southwest corner of the room into a very narrow passageway.)~", 
    R"~(Timber Room)~", 
    { Ex(direction::North, R"~(BLADD)~"), Ex(direction::Sw, std::make_shared<SetgExit>("dark_room", std::make_shared<CExit>(FlagId::empty_handed, "BSHAF", nofit))) }, 
    { "OTIMB"}, 
    room_funcs::no_objs(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit } ),
mr(R"~(BSHAF)~", 
    R"~(This is a small square room which is at the bottom of a long
shaft. To the east is a passageway and to the northeast a very narrow
passage. In the shaft can be seen a heavy iron chain.)~", 
    R"~(Lower Shaft)~", 
    { Ex(direction::East, R"~(MACHI)~"), Ex(direction::Out, std::make_shared<CExit>(FlagId::empty_handed, "TIMBE", nofit)), Ex(direction::Ne, std::make_shared<CExit>(FlagId::empty_handed, "TIMBE", nofit)), Ex(direction::Up, NExit(R"~(The chain is not climbable.)~")) }, 
    { "FBASK"}, 
    room_funcs::no_objs(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit } ),
mr(R"~(MACHI)~", 
    R"~()~", 
    R"~(Machine Room)~", 
    { Ex(direction::Nw, R"~(BSHAF)~") }, 
    { "MSWIT", 
      "MACHI"}, 
    room_funcs::machine_room()),
mr(R"~(BATS)~", 
    R"~()~", 
    R"~(Bat Room)~", 
    { Ex(direction::East, R"~(SQUEE)~") }, 
    { "JADE", 
      "BAT"}, 
    room_funcs::bats_room(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit } ),
mr(R"~(MINE1)~", 
    mindesc, 
    smindesc, 
    { Ex(direction::North, R"~(MINE4)~"), Ex(direction::Sw, R"~(MINE2)~"), Ex(direction::East, R"~(TUNNE)~") }, 
    { }),
mr(R"~(MINE2)~", 
    mindesc, 
    smindesc, 
    { Ex(direction::South, R"~(MINE1)~"), Ex(direction::West, R"~(MINE5)~"), Ex(direction::Up, R"~(MINE3)~"), Ex(direction::Ne, R"~(MINE4)~") }, 
    { }),
mr(R"~(MINE3)~", 
    mindesc, 
    smindesc, 
    { Ex(direction::West, R"~(MINE2)~"), Ex(direction::Ne, R"~(MINE5)~"), Ex(direction::East, R"~(MINE5)~") }, 
    { }),
mr(R"~(MINE4)~", 
    mindesc, 
    smindesc, 
    { Ex(direction::Up, R"~(MINE5)~"), Ex(direction::Ne, R"~(MINE6)~"), Ex(direction::South, R"~(MINE1)~"), Ex(direction::West, R"~(MINE2)~") }, 
    { }),
mr(R"~(MINE5)~", 
    mindesc, 
    smindesc, 
    { Ex(direction::Down, R"~(MINE6)~"), Ex(direction::North, R"~(MINE7)~"), Ex(direction::West, R"~(MINE2)~"), Ex(direction::South, R"~(MINE3)~"), Ex(direction::Up, R"~(MINE3)~"), Ex(direction::East, R"~(MINE4)~") }, 
    { }),
mr(R"~(MINE6)~", 
    mindesc, 
    smindesc, 
    { Ex(direction::Se, R"~(MINE4)~"), Ex(direction::Up, R"~(MINE5)~"), Ex(direction::Nw, R"~(MINE7)~") }, 
    { }),
mr(R"~(MINE7)~", 
    mindesc, 
    smindesc, 
    { Ex(direction::East, R"~(MINE1)~"), Ex(direction::West, R"~(MINE5)~"), Ex(direction::Down, R"~(TLADD)~"), Ex(direction::South, R"~(MINE6)~") }, 
    { }),
mr(R"~(DOME)~", 
    R"~()~", 
    R"~(Dome Room)~", 
    { Ex(direction::East, R"~(CRAW1)~"), Ex(direction::Down, std::make_shared<CExit>(FlagId::dome_flag, "MTORC", "You cannot go down without fracturing many bones.")) }, 
    { "RAILI"}, 
    room_funcs::dome_room()),
mr(R"~(MTORC)~", 
    R"~()~", 
    R"~(Torch Room)~", 
    { Ex(direction::Up, NExit(R"~(You cannot reach the rope.)~")), Ex(direction::West, R"~(PRM)~"), Ex(direction::Down, R"~(CRAW4)~") }, 
    { "TORCH"}, 
    room_funcs::torch_room()),
mr(R"~(CRAW4)~", 
    R"~(This is a north-south crawlway; a passage goes to the east also.
There is a hole above, but it provides no opportunities for climbing.)~", 
    R"~(North-South Crawlway)~", 
    { Ex(direction::North, R"~(CHAS2)~"), Ex(direction::South, R"~(STUDI)~"), Ex(direction::East, R"~(MTROL)~"), Ex(direction::Up, NExit(R"~(Not even a human fly could get up it.)~")) }, 
    { }),
mr(R"~(CHAS2)~", 
    R"~(You are on the west edge of a chasm, the bottom of which cannot be
seen. The east side is sheer rock, providing no exits.  A narrow
passage goes west, and the path you are on continues to the north and
south.)~", 
    R"~(West of Chasm)~", 
    { Ex(direction::West, R"~(CELLA)~"), Ex(direction::North, R"~(CRAW4)~"), Ex(direction::South, R"~(GALLE)~"), Ex(direction::Down, NExit(R"~(The chasm probably leads straight to the infernal regions.)~")) }, 
    { }),
mr(R"~(PASS1)~", 
    R"~(This is a narrow east-west passageway.  There is a narrow stairway
leading down at the north end of the room.)~", 
    R"~(East-West Passage)~", 
    { Ex(direction::East, R"~(CAROU)~"), Ex(direction::West, R"~(MTROL)~"), Ex(direction::Down, R"~(RAVI1)~"), Ex(direction::North, R"~(RAVI1)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rval, 5) }),
mr(R"~(CAROU)~", 
    R"~()~", 
    R"~(Round room)~", 
    { Ex(direction::North, std::make_shared<CExit>(FlagId::carousel_flip, "CAVE4", "", false, exit_funcs::carousel_exit())), Ex(direction::South, std::make_shared<CExit>(FlagId::carousel_flip, "CAVE4", "", false, exit_funcs::carousel_exit())), Ex(direction::East, std::make_shared<CExit>(FlagId::carousel_flip, "MGRAI", "", false, exit_funcs::carousel_exit())), Ex(direction::West, std::make_shared<CExit>(FlagId::carousel_flip, "PASS1", "", false, exit_funcs::carousel_exit())), Ex(direction::Nw, std::make_shared<CExit>(FlagId::carousel_flip, "CANY1", "", false, exit_funcs::carousel_exit())), Ex(direction::Ne, std::make_shared<CExit>(FlagId::carousel_flip, "PASS5", "", false, exit_funcs::carousel_exit())), Ex(direction::Se, std::make_shared<CExit>(FlagId::carousel_flip, "PASS4", "", false, exit_funcs::carousel_exit())), Ex(direction::Sw, std::make_shared<CExit>(FlagId::carousel_flip, "MAZE1", "", false, exit_funcs::carousel_exit())), Ex(direction::Exit, std::make_shared<CExit>(FlagId::carousel_flip, "PASS3", "", false, exit_funcs::carousel_out())) }, 
    { "IRBOX"}, 
    room_funcs::carousel_room()),
mr(R"~(PASS5)~", 
    R"~(This is a high north-south passage, which forks to the northeast.)~", 
    R"~(North-South Passage)~", 
    { Ex(direction::North, R"~(CHAS1)~"), Ex(direction::Ne, R"~(ECHO)~"), Ex(direction::South, R"~(CAROU)~") }, 
    { }),
mr(R"~(CHAS1)~", 
    R"~(A chasm runs southwest to northeast.  You are on the south edge; the
path exits to the south and to the east.)~", 
    R"~(Chasm)~", 
    { Ex(direction::South, R"~(RAVI1)~"), Ex(direction::East, R"~(PASS5)~"), Ex(direction::Down, NExit(R"~(Are you out of your mind?)~")) }, 
    { }),
mr(R"~(CAVE3)~", 
    R"~(This is a cave.  Passages exit to the south and to the east, but
the cave narrows to a crack to the west.  The earth is particularly
damp here.)~", 
    R"~(Damp Cave)~", 
    { Ex(direction::South, R"~(ECHO)~"), Ex(direction::East, R"~(DAM)~"), Ex(direction::West, NExit(R"~(It is too narrow for most insects.)~")) }, 
    { }),
mr(R"~(CHAS3)~", 
    R"~(A chasm, evidently produced by an ancient river, runs through the
cave here.  Passages lead off in all directions.)~", 
    R"~(Ancient Chasm)~", 
    { Ex(direction::South, R"~(ECHO)~"), Ex(direction::East, R"~(TCAVE)~"), Ex(direction::North, R"~(DEAD5)~"), Ex(direction::West, R"~(DEAD6)~") }, 
    { }),
mr(R"~(DEAD5)~", 
    deadend, 
    deadend, 
    { Ex(direction::Sw, R"~(CHAS3)~") }, 
    { }),
mr(R"~(DEAD6)~", 
    deadend, 
    deadend, 
    { Ex(direction::East, R"~(CHAS3)~") }, 
    { }),
mr(R"~(CAVE4)~", 
    R"~(You have entered a cave with passages leading north and southeast.)~", 
    R"~(Engravings Cave)~", 
    { Ex(direction::North, R"~(CAROU)~"), Ex(direction::Se, R"~(RIDDL)~") }, 
    { "ENGRA"}),
mr(R"~(RIDDL)~", 
    R"~(This is a room which is bare on all sides.  There is an exit down. 
To the east is a great door made of stone.  Above the stone, the
following words are written: 'No man shall enter this room without
solving this riddle:

  What is tall as a house,
	  round as a cup, 
	  and all the king's horses can't draw it up?'

(Reply via 'ANSWER "answer"'))~", 
    R"~(Riddle Room)~", 
    { Ex(direction::Down, R"~(CAVE4)~"), Ex(direction::East, std::make_shared<CExit>(FlagId::riddle_flag, "MPEAR", "Your way is blocked by an invisible force.")) }, 
    { "SDOOR"}),
mr(R"~(MPEAR)~", 
    R"~(This is a former broom closet.  The exits are to the east and west.)~", 
    R"~(Pearl Room)~", 
    { Ex(direction::East, R"~(BWELL)~"), Ex(direction::West, R"~(RIDDL)~") }, 
    { "PEARL"}),
mr(R"~(LLD1)~", 
    R"~()~", 
    R"~(Entrance to Hades)~", 
    { Ex(direction::East, std::make_shared<CExit>(FlagId::lld_flag, "LLD2", "Some invisible force prevents you from passing through the gate.")), Ex(direction::Up, R"~(CAVE2)~"), Ex(direction::Enter, std::make_shared<CExit>(FlagId::lld_flag, "LLD2", "Some invisible force prevents you from passing through the gate.")) }, 
    { "CORPS", 
      "GATES", 
      "GHOST"}, 
    room_funcs::lld_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(LLD2)~", 
    R"~()~", 
    R"~(Land of the Living Dead)~", 
    { Ex(direction::East, R"~(TOMB)~"), Ex(direction::Exit, R"~(LLD1)~"), Ex(direction::West, R"~(LLD1)~") }, 
    { "BODIE"}, 
    room_funcs::lld2_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rval, 30) }),
mr(R"~(MGRAI)~", 
    R"~(You are standing in a small circular room with a pedestal.  A set of
stairs leads up, and passages leave to the east and west.)~", 
    R"~(Grail Room)~", 
    { Ex(direction::West, R"~(CAROU)~"), Ex(direction::East, R"~(CRAW3)~"), Ex(direction::Up, R"~(TEMP1)~") }, 
    { "GRAIL"}),
mr(R"~(TEMP1)~", 
    R"~(This is the west end of a large temple.  On the south wall is an 
ancient inscription, probably a prayer in a long-forgotten language. 
The north wall is solid granite.  The entrance at the west end of the
room is through huge marble pillars.)~", 
    R"~(Temple)~", 
    { Ex(direction::West, R"~(MGRAI)~"), Ex(direction::East, R"~(TEMP2)~") }, 
    { "PRAYE", 
      "BELL"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rsacredbit } ),
mr(R"~(TEMP2)~", 
    R"~(This is the east end of a large temple.  In front of you is what
appears to be an altar.)~", 
    R"~(Altar)~", 
    { Ex(direction::West, R"~(TEMP1)~") }, 
    { "BOOK", 
      "CANDL"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rsacredbit } ),
mr(R"~(DAM)~", 
    R"~()~", 
    R"~(Dam)~", 
    { Ex(direction::South, R"~(CANY1)~"), Ex(direction::Down, R"~(DOCK)~"), Ex(direction::East, R"~(CAVE3)~"), Ex(direction::North, R"~(LOBBY)~") }, 
    { "BOLT", 
      "DAM", 
      "BUBBL", 
      "CPANL"}, 
    room_funcs::dam_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(LOBBY)~", 
    R"~(This room appears to have been the waiting room for groups touring
the dam.  There are exits here to the north and east marked
'Private', though the doors are open, and an exit to the south.)~", 
    R"~(Dam Lobby)~", 
    { Ex(direction::South, R"~(DAM)~"), Ex(direction::North, R"~(MAINT)~"), Ex(direction::East, R"~(MAINT)~") }, 
    { "MATCH", 
      "GUIDE"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(MAINT)~", 
    R"~(This is what appears to have been the maintenance room for Flood
Control Dam #3, judging by the assortment of tool chests around the
room.  Apparently, this room has been ransacked recently, for most of
the valuable equipment is gone. On the wall in front of you is a
group of buttons, which are labelled in EBCDIC. However, they are of
different colors:  Blue, Yellow, Brown, and Red. The doors to this
room are in the west and south ends.)~", 
    R"~(Maintenance Room)~", 
    { Ex(direction::South, R"~(LOBBY)~"), Ex(direction::West, R"~(LOBBY)~") }, 
    { "LEAK", 
      "TUBE", 
      "WRENC", 
      "BLBUT", 
      "RBUTT", 
      "BRBUT", 
      "YBUTT", 
      "SCREW", 
      "TCHST"}, 
    room_funcs::maint_room(), 
    { RoomBit::rlandbit} ),
mr(R"~(DOCK)~", 
    R"~(You are at the base of Flood Control Dam #3, which looms above you
and to the north.  The river Frigid is flowing by here.  Across the
river are the White Cliffs which seem to form a giant wall stretching
from north to south along the east shore of the river as it winds its
way downstream.)~", 
    R"~(Dam Base)~", 
    { Ex(direction::North, R"~(DAM)~"), Ex(direction::Up, R"~(DAM)~"), Ex(direction::Launc, R"~(RIVR1)~") }, 
    { "IBOAT", 
      "STICK"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RIVR1)~", 
    R"~(You are on the River Frigid in the vicinity of the Dam.  The river
flows quietly here.  There is a landing on the west shore.)~", 
    riverdesc, 
    { Ex(direction::Up, current_RIVR1), Ex(direction::West, R"~(DOCK)~"), Ex(direction::Land, R"~(DOCK)~"), Ex(direction::Down, R"~(RIVR2)~"), Ex(direction::East, cliffs_RIVR1) }, 
    { }, 
    nullptr, 
    { RoomBit::rwaterbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RIVR2)~", 
    R"~(The River turns a corner here making it impossible to see the
Dam.  The White Cliffs loom on the east bank and large rocks prevent
landing on the west.)~", 
    riverdesc, 
    { Ex(direction::Up, current_RIVR2), Ex(direction::Down, R"~(RIVR3)~"), Ex(direction::East, cliffs_RIVR2) }, 
    { }, 
    nullptr, 
    { RoomBit::rwaterbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RIVR3)~", 
    R"~(The river descends here into a valley.  There is a narrow beach on
the east below the cliffs and there is some shore on the west which
may be suitable.  In the distance a faint rumbling can be heard.)~", 
    riverdesc, 
    { Ex(direction::Up, current_RIVR3), Ex(direction::Down, R"~(RIVR4)~"), Ex(direction::East, R"~(WCLF1)~"), Ex(direction::West, R"~(RCAVE)~"), Ex(direction::Land, NExit(R"~(You must specify which direction here.)~")) }, 
    { }, 
    nullptr, 
    { RoomBit::rwaterbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(WCLF1)~", 
    R"~(You are on a narrow strip of beach which runs along the base of the
White Cliffs. The only path here is a narrow one, heading south
along the Cliffs.)~", 
    R"~(White Cliffs Beach)~", 
    { Ex(direction::South, std::make_shared<CExit>(FlagId::deflate, "WCLF2", narrow)), Ex(direction::Launc, R"~(RIVR3)~") }, 
    { "WCLIF"}, 
    room_funcs::cliff_function(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit, RoomBit::rnwallbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(WCLF2)~", 
    R"~(You are on a rocky, narrow strip of beach beside the Cliffs.  A
narrow path leads north along the shore.)~", 
    R"~(White Cliffs Beach)~", 
    { Ex(direction::North, std::make_shared<CExit>(FlagId::deflate, "WCLF1", narrow)), Ex(direction::Launc, R"~(RIVR4)~") }, 
    { "WCLIF"}, 
    room_funcs::cliff_function(), 
    { RoomBit::rnwallbit, RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RIVR4)~", 
    R"~(The river is running faster here and the sound ahead appears to be
that of rushing water.  On the west shore is a sandy beach.  A small
area of beach can also be seen below the Cliffs.)~", 
    riverdesc, 
    { Ex(direction::Up, current_RIVR4), Ex(direction::Down, R"~(RIVR5)~"), Ex(direction::East, R"~(WCLF2)~"), Ex(direction::West, R"~(BEACH)~"), Ex(direction::Land, NExit(R"~(Specify the direction to land.)~")) }, 
    { "BUOY"}, 
    room_funcs::rivr4_room(), 
    { RoomBit::rwaterbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RIVR5)~", 
    R"~(The sound of rushing water is nearly unbearable here.  On the west
shore is a large landing area.)~", 
    riverdesc, 
    { Ex(direction::Up, current_RIVR5), Ex(direction::Down, R"~(FCHMP)~"), Ex(direction::Land, R"~(FANTE)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rwaterbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(FCHMP)~", 
    R"~()~", 
    R"~(Moby lossage)~", 
    { Ex(direction::North, NExit(R"~()~")) }, 
    { }, 
    room_funcs::over_falls()),
mr(R"~(FANTE)~", 
    R"~(You are on the shore of the River.  The river here seems somewhat
treacherous.  A path travels from north to south here, the south end
quickly turning around a sharp corner.)~", 
    R"~(Shore)~", 
    { Ex(direction::Launc, R"~(RIVR5)~"), Ex(direction::North, R"~(BEACH)~"), Ex(direction::South, R"~(FALLS)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rnwallbit, RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(BEACH)~", 
    R"~(You are on a large sandy beach at the shore of the river, which is
flowing quickly by.  A path runs beside the river to the south here.)~", 
    R"~(Sandy Beach)~", 
    { Ex(direction::Launc, R"~(RIVR4)~"), Ex(direction::South, R"~(FANTE)~") }, 
    { "STATU", 
      "SAND"}, 
    nullptr, 
    { RoomBit::rnwallbit, RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RCAVE)~", 
    R"~(You are on the west shore of the river.  An entrance to a cave is
to the northwest.  The shore is very rocky here.)~", 
    R"~(Rocky Shore)~", 
    { Ex(direction::Launc, R"~(RIVR3)~"), Ex(direction::Nw, R"~(TCAVE)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rnwallbit, RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(TCAVE)~", 
    R"~(This is a small cave whose exits are on the south and northwest.)~", 
    R"~(Small Cave)~", 
    { Ex(direction::South, R"~(RCAVE)~"), Ex(direction::Nw, R"~(CHAS3)~") }, 
    { "GUANO", 
      "SHOVE"}),
mr(R"~(FALLS)~", 
    R"~()~", 
    R"~(Aragain Falls)~", 
    { Ex(direction::East, std::make_shared<CExit>(FlagId::rainbow, "RAINB", "")), Ex(direction::Down, NExit(R"~(It's a long way...)~")), Ex(direction::North, R"~(FANTE)~"), Ex(direction::Up, std::make_shared<CExit>(FlagId::rainbow, "RAINB", "")) }, 
    { "RAINB", 
      "BARRE"}, 
    room_funcs::falls_room(), 
    { RoomBit::rnwallbit, RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(RAINB)~", 
    R"~(You are on top of a rainbow (I bet you never thought you would walk
on a rainbow), with a magnificent view of the Falls.  The rainbow
travels east-west here.  There is an NBC Commissary here.)~", 
    R"~(Rainbow Room)~", 
    { Ex(direction::East, R"~(POG)~"), Ex(direction::West, R"~(FALLS)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } ),
mr(R"~(POG)~", 
    R"~(You are on a small, rocky beach on the continuation of the Frigid
River past the Falls.  The beach is narrow due to the presence of the
White Cliffs.  The river canyon opens here and sunlight shines in
from above. A rainbow crosses over the falls to the west and a narrow
path continues to the southeast.)~", 
    R"~(End of Rainbow)~", 
    { Ex(direction::Up, crain_POG), Ex(direction::Nw, crain_POG), Ex(direction::West, crain_POG), Ex(direction::Se, R"~(CLBOT)~"), Ex(direction::Launc, NExit(R"~(The sharp rocks endanger your boat.)~")) }, 
    { "RAINB", 
      "POT"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(CLBOT)~", 
    R"~(You are beneath the walls of the river canyon which may be climbable
here.  There is a small stream here, which is the lesser part of the
runoff of Aragain Falls. To the north is a narrow path.)~", 
    R"~(Canyon Bottom)~", 
    { Ex(direction::Up, R"~(CLMID)~"), Ex(direction::North, R"~(POG)~") }, 
    { "CCLIF"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rgwater })) }),
mr(R"~(CLMID)~", 
    R"~(You are on a ledge about halfway up the wall of the river canyon.
You can see from here that the main flow from Aragain Falls twists
along a passage which it is impossible to enter.  Below you is the
canyon bottom.  Above you is more cliff, which still appears
climbable.)~", 
    R"~(Rocky Ledge)~", 
    { Ex(direction::Up, R"~(CLTOP)~"), Ex(direction::Down, R"~(CLBOT)~") }, 
    { "CCLIF"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } ),
mr(R"~(CLTOP)~", 
    R"~(You are at the top of the Great Canyon on its south wall.  From here
there is a marvelous view of the Canyon and parts of the Frigid River
upstream.  Across the canyon, the walls of the White Cliffs still
appear to loom far above.  Following the Canyon upstream (north and
northwest), Aragain Falls may be seen, complete with rainbow. 
Fortunately, my vision is better than average and I can discern the
top of the Flood Control Dam #3 far to the distant north.  To the
west and south can be seen an immense forest, stretching for miles
around.  It is possible to climb down into the canyon from here.)~", 
    R"~(Canyon View)~", 
    { Ex(direction::Down, R"~(CLMID)~"), Ex(direction::South, R"~(FORE4)~"), Ex(direction::West, R"~(FORE5)~") }, 
    { "CCLIF"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rnwallbit, RoomBit::rsacredbit } ),
mr(R"~(VLBOT)~", 
    R"~(You are at the bottom of a large dormant volcano.  High above you
light may be seen entering from the cone of the volcano.  The only
exit here is to the north.)~", 
    R"~(Volcano Bottom)~", 
    { Ex(direction::North, R"~(LAVA)~") }, 
    { "BALLO"}),
mr(R"~(VAIR1)~", 
    R"~(You are about one hundred feet above the bottom of the volcano.  The
top of the volcano is clearly visible here.)~", 
    R"~(Volcano Core)~", 
    { }, 
    { }, 
    nullptr, 
    { RoomBit::rairbit, RoomBit::rnwallbit, RoomBit::rsacredbit } ),
mr(R"~(VAIR2)~", 
    R"~(You are about two hundred feet above the volcano floor.  Looming
above is the rim of the volcano.  There is a small ledge on the west
side.)~", 
    R"~(Volcano near small ledge)~", 
    { Ex(direction::West, R"~(LEDG2)~"), Ex(direction::Land, R"~(LEDG2)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rairbit, RoomBit::rnwallbit, RoomBit::rsacredbit } ),
mr(R"~(VAIR3)~", 
    R"~(You are high above the floor of the volcano.  From here the rim of
the volcano looks very narrow and you are very near it.  To the 
east is what appears to be a viewing ledge, too thin to land on.)~", 
    R"~(Volcano near viewing ledge)~", 
    { }, 
    { }, 
    nullptr, 
    { RoomBit::rairbit, RoomBit::rnwallbit, RoomBit::rsacredbit } ),
mr(R"~(VAIR4)~", 
    R"~(You are near the rim of the volcano which is only about 15 feet
across.  To the west, there is a place to land on a wide ledge.)~", 
    R"~(Volcano near wide ledge)~", 
    { Ex(direction::Land, R"~(LEDG4)~"), Ex(direction::East, R"~(LEDG4)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rairbit, RoomBit::rnwallbit, RoomBit::rsacredbit } ),
mr(R"~(LEDG2)~", 
    R"~(You are on a narrow ledge overlooking the inside of an old dormant
volcano.  This ledge appears to be about in the middle between the
floor below and the rim above. There is an exit here to the south.)~", 
    R"~(Narrow Ledge)~", 
    { Ex(direction::Down, NExit(R"~(I wouldn't jump from here.)~")), Ex(direction::Launc, R"~(VAIR2)~"), Ex(direction::West, cxgnome_LEDG2), Ex(direction::South, R"~(LIBRA)~") }, 
    { "HOOK1", 
      "COIN"}),
mr(R"~(LIBRA)~", 
    R"~(This is a room which must have been a large library, probably
for the royal family.  All of the shelves appear to have been gnawed
to pieces by unfriendly gnomes.  To the north is an exit.)~", 
    R"~(Library)~", 
    { Ex(direction::North, R"~(LEDG2)~"), Ex(direction::Out, R"~(LEDG2)~") }, 
    { "BLBK", 
      "GRBK", 
      "PUBK", 
      "WHBK"}),
mr(R"~(LEDG3)~", 
    R"~(You are on a ledge in the middle of a large volcano.  Below you
the volcano bottom can be seen and above is the rim of the volcano.
A couple of ledges can be seen on the other side of the volcano;
it appears that this ledge is intermediate in elevation between
those on the other side.  The exit from this room is to the east.)~", 
    R"~(Volcano View)~", 
    { Ex(direction::Down, NExit(R"~(I wouldn't try that.)~")), Ex(direction::Cross, NExit(R"~(It is impossible to cross this distance.)~")), Ex(direction::East, R"~(EGYPT)~") }, 
    { }),
mr(R"~(LEDG4)~", 
    R"~()~", 
    R"~(Wide Ledge)~", 
    { Ex(direction::Down, NExit(R"~(It's a long way down.)~")), Ex(direction::Launc, R"~(VAIR4)~"), Ex(direction::West, cxgnome_LEDG4), Ex(direction::South, R"~(SAFE)~") }, 
    { "HOOK2"}, 
    room_funcs::ledge_function()),
mr(R"~(SAFE)~", 
    R"~()~", 
    R"~(Dusty Room)~", 
    { Ex(direction::North, R"~(LEDG4)~") }, 
    { "SSLOT", 
      "SAFE"}, 
    room_funcs::safe_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(LAVA)~", 
    R"~(This is a small room, whose walls are formed by an old lava flow.
There are exits here to the west and the south.)~", 
    R"~(Lava Room)~", 
    { Ex(direction::South, R"~(VLBOT)~"), Ex(direction::West, R"~(RUBYR)~") }, 
    { }),
mr(R"~(MAGNE)~", 
    R"~()~", 
    R"~(Low Room)~", 
    { Ex(direction::North, magcmach_MAGNE), Ex(direction::South, magcmach_MAGNE), Ex(direction::West, magcmach_MAGNE), Ex(direction::Ne, magcmach_MAGNE), Ex(direction::Nw, magalice_MAGNE), Ex(direction::Sw, magalice_MAGNE), Ex(direction::Se, magalice_MAGNE), Ex(direction::East, magcmach_MAGNE), Ex(direction::Out, magalice_MAGNE) }, 
    { "RBTLB", 
      "ROBOT"}, 
    room_funcs::magnet_room()),
mr(R"~(CMACH)~", 
    R"~()~", 
    R"~(Machine Room)~", 
    { Ex(direction::West, R"~(MAGNE)~"), Ex(direction::South, R"~(CAGER)~") }, 
    { "SQBUT", 
      "RNBUT", 
      "TRBUT"}, 
    room_funcs::cmach_room()),
mr(R"~(CAGER)~", 
    R"~(This is a dingy closet adjacent to the machine room.  On one wall
is a small sticker which says
		Protected by
		  FROBOZZ
	     Magic Alarm Company
	      (Hello, footpad!)
)~", 
    R"~(Dingy Closet)~", 
    { Ex(direction::North, R"~(CMACH)~") }, 
    { "SPHER"}, 
    nullptr, 
    { RoomBit::rlightbit, RoomBit::rlandbit } ),
mr(R"~(CAGED)~", 
    R"~(You are trapped inside a steel cage.)~", 
    R"~(Cage)~", 
    { Ex(direction::North, NExit(R"~()~")) }, 
    { "CAGE"}, 
    room_funcs::caged_room(), 
    { RoomBit::rlandbit, RoomBit::rnwallbit } ),
mr(R"~(TWELL)~", 
    R"~(You are at the top of the well.  Well done.  There are etchings on
the side of the well. There is a small crack across the floor at the
entrance to a room on the east, but it can be crossed easily.)~", 
    R"~(Top of Well)~", 
    { Ex(direction::East, R"~(ALICE)~"), Ex(direction::Down, NExit(R"~(It's a long way down!)~")) }, 
    { "ETCH2"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rbuckbit } , 
    { RP(ObjectSlots::ksl_rval, 10), RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::wellbit })) }),
mr(R"~(BWELL)~", 
    R"~(This is a damp circular room, whose walls are made of brick and
mortar.  The roof of this room is not visible, but there appear to be
some etchings on the walls.  There is a passageway to the west.)~", 
    R"~(Circular Room)~", 
    { Ex(direction::West, R"~(MPEAR)~"), Ex(direction::Up, NExit(R"~(The walls cannot be climbed.)~")) }, 
    { "BUCKE", 
      "ETCH1"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rbuckbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::wellbit })) }),
mr(R"~(ALICE)~", 
    R"~(This is a small square room, in the center of which is a large
oblong table, no doubt set for afternoon tea.  It is clear from the
objects on the table that the users were indeed mad.  In the eastern
corner of the room is a small hole (no more than four inches high). 
There are passageways leading away to the west and the northwest.)~", 
    R"~(Tea Room)~", 
    { Ex(direction::East, NExit(R"~(Only a mouse could get in there.)~")), Ex(direction::West, R"~(TWELL)~"), Ex(direction::Nw, R"~(MAGNE)~") }, 
    { "ATABL", 
      "ECAKE", 
      "ORICE", 
      "RDICE", 
      "BLICE"}),
mr(R"~(ALISM)~", 
    R"~(This is an enormous room, in the center of which are four wooden
posts delineating a rectangular area, above which is what appears to
be a wooden roof.  In fact, all objects in this room appear to be
abnormally large. To the east is a passageway.  There is a large
chasm on the west and the northwest.)~", 
    R"~(Posts Room)~", 
    { Ex(direction::Nw, smdrop_ALISM), Ex(direction::East, R"~(ALITR)~"), Ex(direction::West, smdrop_ALISM), Ex(direction::Down, smdrop_ALISM) }, 
    { "POSTS"}),
mr(R"~(ALITR)~", 
    R"~(This is a large room, one half of which is depressed.  There is a
large leak in the ceiling through which brown colored goop is
falling.  The only exit to this room is to the west.)~", 
    R"~(Pool Room)~", 
    { Ex(direction::Exit, R"~(ALISM)~"), Ex(direction::West, R"~(ALISM)~") }, 
    { "FLASK", 
      "POOL", 
      "PLEAK", 
      "SAFFR"}),
mr(R"~(BKENT)~", 
    R"~(This is the large entrance hall of the Bank of Zork, the largest
banking institution of the Great Underground Empire. A partial
account of its history is in 'The Lives of the Twelve Flatheads' with
the chapter on J. Pierpont Flathead.  A more detailed history (albeit
less objective) may be found in Flathead's outrageous autobiography
'I'm Rich and You Aren't - So There!'.
Most of the furniture has been ravaged by passing scavengers.  All
that remains are two signs at the Northwest and Northeast corners of
the room, which say
  
      <--  WEST VIEWING ROOM        EAST VIEWING ROOM  -->  
)~", 
    R"~(Bank Entrance)~", 
    { Ex(direction::Nw, R"~(BKTW)~"), Ex(direction::Ne, R"~(BKTE)~"), Ex(direction::South, R"~(GALLE)~") }, 
    { }),
mr(R"~(BKTW)~", 
    R"~()~", 
    R"~(West Teller's Room)~", 
    { Ex(direction::North, R"~(BKVW)~"), Ex(direction::South, R"~(BKENT)~"), Ex(direction::West, R"~(BKBOX)~") }, 
    { }, 
    room_funcs::teller_room()),
mr(R"~(BKTE)~", 
    R"~()~", 
    R"~(East Teller's Room)~", 
    { Ex(direction::North, R"~(BKVE)~"), Ex(direction::South, R"~(BKENT)~"), Ex(direction::East, R"~(BKBOX)~") }, 
    { }, 
    room_funcs::teller_room()),
mr(R"~(BKVW)~", 
    view_room, 
    R"~(Viewing Room)~", 
    { Ex(direction::South, R"~(BKENT)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::wall_eswbit, Bits::wall_nbit })) }),
mr(R"~(BKVE)~", 
    view_room, 
    R"~(Viewing Room)~", 
    { Ex(direction::South, R"~(BKENT)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::wall_eswbit, Bits::wall_nbit })) }),
mr(R"~(BKTWI)~", 
    R"~(This is a small, bare room with no distinguishing features. There
are no exits from this room.)~", 
    R"~(Small Room)~", 
    { }, 
    { }, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::wall_eswbit, Bits::wall_nbit })) }),
mr(R"~(BKVAU)~", 
    R"~(This is the Vault of the Bank of Zork, in which there are no doors.)~", 
    R"~(Vault)~", 
    { }, 
    { "BILLS"}, 
    nullptr, 
    { RoomBit::rsacredbit, RoomBit::rlandbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::wall_eswbit, Bits::wall_nbit })) }),
mr(R"~(BKBOX)~", 
    R"~(This is a large rectangular room.  The east and west walls here
were used for storing safety deposit boxes.  As might be expected,
all have been carefully removed by evil persons.  To the east, west,
and south of the room are large doorways. The northern 'wall'
of the room is a shimmering curtain of light.  In the center of the
room is a large stone cube, about 10 feet on a side.  Engraved on 
the side of the cube is some lettering.)~", 
    R"~(Safety Depository)~", 
    { Ex(direction::North, NExit(R"~(There is a curtain of light there.)~")), Ex(direction::West, std::make_shared<CExit>(frobozz(), "BKTW", bkalarm, false, exit_funcs::bkleavew())), Ex(direction::East, std::make_shared<CExit>(frobozz(), "BKTE", bkalarm, false, exit_funcs::bkleavee())), Ex(direction::South, R"~(BKEXE)~") }, 
    { "VAULT", 
      "SCOL"}, 
    room_funcs::bkbox_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::wall_nbit })) }),
mr(R"~(BKEXE)~", 
    R"~(This room was the office of the Chairman of the Bank of Zork.
Like the other rooms here, it has been extensively vandalized.
The lone exit is to the north.)~", 
    R"~(Chairman's Office)~", 
    { Ex(direction::North, R"~(BKBOX)~") }, 
    { "PORTR"}),
mr(R"~(CPANT)~", 
    R"~(This is a small square room, in the middle of which is a recently 
created hole through which you can barely discern the floor some ten
feet below.  It doesn't seem likely you could climb back up.  There
are exits to the west and south.)~", 
    R"~(Small Square Room)~", 
    { Ex(direction::South, R"~(CPOUT)~"), Ex(direction::West, R"~(TREAS)~"), Ex(direction::Down, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpenter())) }, 
    { "WARNI"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(CPOUT)~", 
    R"~()~", 
    R"~(Side Room)~", 
    { Ex(direction::North, R"~(CPANT)~"), Ex(direction::East, std::make_shared<CExit>(FlagId::cpout, "CP", "The steel door bars the way.")) }, 
    { "CPDR2"}, 
    room_funcs::cpout_room()),
mr(R"~(CP)~", 
    R"~()~", 
    R"~(Room in a Puzzle)~", 
    { Ex(direction::North, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())), Ex(direction::South, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())), Ex(direction::East, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())), Ex(direction::West, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())), Ex(direction::Ne, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())), Ex(direction::Nw, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())), Ex(direction::Se, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())), Ex(direction::Up, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())), Ex(direction::Sw, std::make_shared<CExit>(frobozz(), "FCHMP", "", false, exit_funcs::cpexit())) }, 
    { }, 
    room_funcs::cp_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::cpladder, Bits::cpwall })) }),
mr(R"~(PALAN)~", 
    R"~()~", 
    R"~(Dreary Room)~", 
    { Ex(direction::South, palandoor_PALAN), Ex(direction::Exit, palandoor_PALAN), Ex(direction::NullExit, palanwind_PALAN) }, 
    { "PDOOR", 
      "PWIND", 
      "PLID2", 
      "PKH2", 
      "PALAN", 
      "PTABL", 
      "PCRAK"}, 
    room_funcs::palantir_room(), 
    { RoomBit::rlandbit, RoomBit::rlightbit, RoomBit::rsacredbit } ),
mr(R"~(PRM)~", 
    R"~()~", 
    R"~(Tiny Room)~", 
    { Ex(direction::North, palandoor_PRM), Ex(direction::Enter, palandoor_PRM), Ex(direction::NullExit, palanwind_PRM), Ex(direction::East, R"~(MTORC)~") }, 
    { "PDOOR", 
      "PWIND", 
      "PLID1", 
      "PKH1"}, 
    room_funcs::prm_room()),
mr(R"~(SLIDE)~", 
    R"~()~", 
    R"~(Slide Room)~", 
    { Ex(direction::East, R"~(PASS3)~"), Ex(direction::North, R"~(ENTRA)~"), Ex(direction::Down, std::make_shared<CExit>(frobozz(), "CAVE4", "", false, exit_funcs::slide_exit())) }, 
    { }, 
    room_funcs::slide_room(), 
    { RoomBit::rlandbit} , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::slidebit })) }),
mr(R"~(SLID1)~", 
    R"~(This is an uncomfortable spot within the coal chute.  The rope to
which you are clinging can be seen rising into the darkness above.
There is more rope dangling below you.)~", 
    R"~(Slide)~", 
    { Ex(direction::Down, R"~(SLID2)~"), Ex(direction::Up, R"~(SLIDE)~") }, 
    { }, 
    room_funcs::inslide(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::ropebit, Bits::slidebit })) }),
mr(R"~(SLID2)~", 
    R"~(This is another spot within the coal chute.  Above you the rope
climbs into darkness and the end of the rope is dangling five feet
beneath you.)~", 
    R"~(Slide)~", 
    { Ex(direction::Down, R"~(SLID3)~"), Ex(direction::Up, R"~(SLID1)~") }, 
    { }, 
    room_funcs::inslide(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::ropebit, Bits::slidebit })) }),
mr(R"~(SLID3)~", 
    R"~(You have reached the end of your rope.  Below you is darkness as
the chute makes a sharp turn.  On the east here is a small ledge
which you might be able to stand on.)~", 
    R"~(Slide)~", 
    { Ex(direction::Down, R"~(CELLA)~"), Ex(direction::Up, R"~(SLID2)~"), Ex(direction::East, R"~(SLEDG)~") }, 
    { }, 
    room_funcs::inslide(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::ropebit, Bits::slidebit })) }),
mr(R"~(SLEDG)~", 
    R"~(This is a narrow ledge abutting the coal chute, in which a rope can
be seen passing downward.  Behind you, to the south, is a small room.)~", 
    R"~(Slide Ledge)~", 
    { Ex(direction::Down, R"~(CELLA)~"), Ex(direction::Up, R"~(SLID2)~"), Ex(direction::South, R"~(SPAL)~") }, 
    { }, 
    room_funcs::sledg_room(), 
    { RoomBit::rlandbit, RoomBit::rsacredbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::ropebit, Bits::slidebit })) }),
mr(R"~(SPAL)~", 
    R"~(This is a small room with rough walls, and a ceiling which is steeply
sloping from north to south. There is coal dust covering almost
everything, and little bits of coal are scattered around the only exit
(which is a narrow passage to the north). In one corner of the room is
an old coal stove which lights the room with a cheery red glow.  There
is a very narrow crack in the north wall.)~", 
    R"~(Sooty Room)~", 
    { Ex(direction::North, R"~(SLEDG)~") }, 
    { "PAL3", 
      "STOVE"}, 
    nullptr, 
    { RoomBit::rlandbit, RoomBit::rsacredbit, RoomBit::rlightbit } ),
mr(R"~(MRD)~", 
    R"~()~", 
    R"~(Hallway)~", 
    { Ex(direction::North, R"~(FDOOR)~"), Ex(direction::Ne, R"~(FDOOR)~"), Ex(direction::Nw, R"~(FDOOR)~"), Ex(direction::South, mr_g_MRD), Ex(direction::Se, mr_g_MRD), Ex(direction::Sw, mr_g_MRD) }, 
    { }, 
    room_funcs::mrdf(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rosebit, Bits::chanbit, Bits::guardbit })) }),
mr(R"~(MRG)~", 
    R"~()~", 
    R"~(Hallway)~", 
    { Ex(direction::North, mr_d_MRG), Ex(direction::South, mr_c_MRG) }, 
    { }, 
    room_funcs::guardians(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::guardbit })) }),
mr(R"~(MRC)~", 
    R"~()~", 
    R"~(Hallway)~", 
    { Ex(direction::North, mr_g_MRC), Ex(direction::Nw, mr_g_MRC), Ex(direction::Ne, mr_g_MRC), Ex(direction::Enter, mirex_MRC), Ex(direction::South, mr_b_MRC), Ex(direction::Sw, mr_b_MRC), Ex(direction::Se, mr_b_MRC) }, 
    { }, 
    room_funcs::mrcf(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::rosebit, Bits::chanbit, Bits::guardbit })) }),
mr(R"~(MRB)~", 
    R"~()~", 
    R"~(Hallway)~", 
    { Ex(direction::North, mr_c_MRB), Ex(direction::Nw, mr_c_MRB), Ex(direction::Ne, mr_c_MRB), Ex(direction::Enter, mirex_MRB), Ex(direction::South, mr_a_MRB), Ex(direction::Sw, mr_a_MRB), Ex(direction::Se, mr_a_MRB) }, 
    { }, 
    room_funcs::mrbf(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::rosebit, Bits::chanbit })) }),
mr(R"~(MRA)~", 
    R"~()~", 
    R"~(Hallway)~", 
    { Ex(direction::North, mr_b_MRA), Ex(direction::Nw, mr_b_MRA), Ex(direction::Ne, mr_b_MRA), Ex(direction::Enter, mirex_MRA), Ex(direction::South, R"~(MREYE)~") }, 
    { }, 
    room_funcs::mraf(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::rosebit, Bits::chanbit })) }),
mr(R"~(MRDE)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { }, 
    { }, 
    room_funcs::guardians(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::guardbit })) }),
mr(R"~(MRDW)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { }, 
    { }, 
    room_funcs::guardians(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::guardbit })) }),
mr(R"~(MRGE)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { }, 
    { }, 
    room_funcs::guardians(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::guardbit })) }),
mr(R"~(MRGW)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { }, 
    { }, 
    room_funcs::guardians(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::guardbit })) }),
mr(R"~(MRCE)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { Ex(direction::Enter, mirex_MRCE), Ex(direction::West, mirex_MRCE), Ex(direction::North, R"~(MRG)~"), Ex(direction::South, R"~(MRB)~") }, 
    { }, 
    room_funcs::mrcew(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::guardbit })) }),
mr(R"~(MRCW)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { Ex(direction::Enter, mirex_MRCW), Ex(direction::East, mirex_MRCW), Ex(direction::North, R"~(MRG)~"), Ex(direction::South, R"~(MRB)~") }, 
    { }, 
    room_funcs::mrcew(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit, Bits::guardbit })) }),
mr(R"~(MRBE)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { Ex(direction::Enter, mirex_MRBE), Ex(direction::West, mirex_MRBE), Ex(direction::North, R"~(MRC)~"), Ex(direction::South, R"~(MRA)~") }, 
    { }, 
    room_funcs::mrbew(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit })) }),
mr(R"~(MRBW)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { Ex(direction::Enter, mirex_MRBW), Ex(direction::East, mirex_MRBW), Ex(direction::North, R"~(MRC)~"), Ex(direction::South, R"~(MRA)~") }, 
    { }, 
    room_funcs::mrbew(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit })) }),
mr(R"~(MRAE)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { Ex(direction::Enter, mirex_MRAE), Ex(direction::West, mirex_MRAE), Ex(direction::North, R"~(MRB)~"), Ex(direction::South, R"~(MREYE)~") }, 
    { }, 
    room_funcs::mraew(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit })) }),
mr(R"~(MRAW)~", 
    R"~()~", 
    R"~(Narrow Room)~", 
    { Ex(direction::Enter, mirex_MRAW), Ex(direction::East, mirex_MRAW), Ex(direction::North, R"~(MRB)~"), Ex(direction::South, R"~(MREYE)~") }, 
    { }, 
    room_funcs::mraew(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::mirrorbit, Bits::panelbit })) }),
mr(R"~(INMIR)~", 
    R"~()~", 
    R"~(Inside Mirror)~", 
    { Ex(direction::North, mout_INMIR), Ex(direction::South, mout_INMIR), Ex(direction::East, mout_INMIR), Ex(direction::West, mout_INMIR), Ex(direction::Ne, mout_INMIR), Ex(direction::Nw, mout_INMIR), Ex(direction::Se, mout_INMIR), Ex(direction::Sw, mout_INMIR), Ex(direction::Exit, mout_INMIR) }, 
    { "YLWAL", 
      "WHWAL", 
      "RDWAL", 
      "BLWAL", 
      "OAKND", 
      "PINND", 
      "WDBAR", 
      "LPOLE", 
      "SPOLE", 
      "TBAR", 
      "ARROW"}, 
    room_funcs::magic_mirror(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rval, 15), RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::rosebit, Bits::chanbit, Bits::guardbit })) }),
mr(R"~(MRANT)~", 
    R"~(You are standing near one end of a long, dimly lit hall.  At the
south stone stairs ascend.  To the north the corridor is illuminated
by torches set high in the walls, out of reach.  On one wall is a red
button.)~", 
    R"~(Stone Room)~", 
    { Ex(direction::South, R"~(TSTRS)~"), Ex(direction::Up, R"~(TSTRS)~"), Ex(direction::North, R"~(MREYE)~") }, 
    { "RSWIT"}, 
    nullptr, 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(MREYE)~", 
    R"~()~", 
    R"~(Small Room)~", 
    { Ex(direction::North, mr_a_MREYE), Ex(direction::Nw, mr_a_MREYE), Ex(direction::Ne, mr_a_MREYE), Ex(direction::South, R"~(MRANT)~") }, 
    { "RBEAM"}, 
    room_funcs::mreye_room(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(TOMB)~", 
    R"~()~", 
    R"~(Tomb of the Unknown Implementer)~", 
    { Ex(direction::West, R"~(LLD2)~"), Ex(direction::North, cd_TOMB), Ex(direction::Enter, cd_TOMB) }, 
    { "TOMB", 
      "HEADS", 
      "COKES", 
      "LISTS"}, 
    room_funcs::tomb_function()),
mr(R"~(CRYPT)~", 
    R"~()~", 
    R"~(Crypt)~", 
    { Ex(direction::South, cd_CRYPT), Ex(direction::Leave, cd_CRYPT) }, 
    { "TOMB"}, 
    room_funcs::crypt_function(), 
    { RoomBit::rendgame, RoomBit::rlandbit } , 
    { RP(ObjectSlots::ksl_rval, 5) }),
mr(R"~(TSTRS)~", 
    R"~(You are standing at the top of a flight of stairs that lead down to
a passage below.  Dim light, as from torches, can be seen in the
passage.  Behind you the stairs lead into untouched rock.)~", 
    R"~(Top of Stairs)~", 
    { Ex(direction::North, R"~(MRANT)~"), Ex(direction::Down, R"~(MRANT)~"), Ex(direction::South, NExit(R"~(The wall is solid rock.)~")) }, 
    { }, 
    nullptr, 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rval, 10) }),
mr(R"~(ECORR)~", 
    R"~(This is a corridor with polished marble walls.  The corridor
widens into larger areas as it turns west at its northern and
southern ends.)~", 
    R"~(East Corridor)~", 
    { Ex(direction::North, R"~(NCORR)~"), Ex(direction::South, R"~(SCORR)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(WCORR)~", 
    R"~(This is a corridor with polished marble walls.  The corridor
widens into larger areas as it turns east at its northern and
southern ends.)~", 
    R"~(West Corridor)~", 
    { Ex(direction::North, R"~(NCORR)~"), Ex(direction::South, R"~(SCORR)~") }, 
    { }, 
    nullptr, 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(SCORR)~", 
    R"~()~", 
    R"~(South Corridor)~", 
    { Ex(direction::West, R"~(WCORR)~"), Ex(direction::East, R"~(ECORR)~"), Ex(direction::North, od_SCORR), Ex(direction::South, R"~(BDOOR)~") }, 
    { "ODOOR"}, 
    room_funcs::scorr_room(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } ),
mr(R"~(BDOOR)~", 
    R"~()~", 
    R"~(Narrow Corridor)~", 
    { Ex(direction::North, R"~(SCORR)~"), Ex(direction::South, wd_BDOOR) }, 
    { "MASTE", 
      "QDOOR"}, 
    room_funcs::bdoor_function(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rval, 20) }),
mr(R"~(FDOOR)~", 
    R"~()~", 
    R"~(Dungeon Entrance)~", 
    { Ex(direction::North, wd_FDOOR), Ex(direction::Enter, wd_FDOOR), Ex(direction::South, mr_d_FDOOR), Ex(direction::Se, mr_d_FDOOR), Ex(direction::Sw, mr_d_FDOOR) }, 
    { "QDOOR"}, 
    room_funcs::fdoor_function(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rval, 15), RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::masterbit })) }),
mr(R"~(NCORR)~", 
    R"~()~", 
    R"~(North Corridor)~", 
    { Ex(direction::East, R"~(ECORR)~"), Ex(direction::West, R"~(WCORR)~"), Ex(direction::North, R"~(PARAP)~"), Ex(direction::South, cd_NCORR), Ex(direction::Enter, cd_NCORR) }, 
    { "CDOOR"}, 
    room_funcs::ncorr_room(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::masterbit })) }),
mr(R"~(PARAP)~", 
    R"~()~", 
    R"~(Parapet)~", 
    { Ex(direction::South, R"~(NCORR)~"), Ex(direction::North, NExit(R"~(You would be burned to a crisp in no time.)~")) }, 
    { "DBUTT", 
      "DIAL", 
      "ONE", 
      "TWO", 
      "THREE", 
      "FOUR", 
      "FIVE", 
      "SIX", 
      "SEVEN", 
      "EIGHT"}, 
    room_funcs::parapet(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::masterbit })) }),
mr(R"~(CELL)~", 
    R"~()~", 
    R"~(Prison Cell)~", 
    { Ex(direction::Exit, cd_CELL), Ex(direction::North, cd_CELL), Ex(direction::South, od_CELL) }, 
    { "CDOOR", 
      "ODOOR"}, 
    room_funcs::cell_room(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::masterbit })) }),
mr(R"~(PCELL)~", 
    R"~()~", 
    R"~(Prison Cell)~", 
    { Ex(direction::Exit, fout_PCELL) }, 
    { "LDOOR"}, 
    room_funcs::pcell_room(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::masterbit })) }),
mr(R"~(NCELL)~", 
    R"~()~", 
    R"~(Prison Cell)~", 
    { Ex(direction::South, fout_NCELL), Ex(direction::Exit, nd_NCELL), Ex(direction::North, nd_NCELL) }, 
    { "ODOOR", 
      "MDOOR"}, 
    room_funcs::ncell_room(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rglobal, std::vector<Bits>({ Bits::masterbit })) }),
mr(R"~(NIRVA)~", 
    R"~(     This is a room of large size, richly appointed and decorated
in a style that bespeaks exquisite taste.  To judge from its
contents, it is the ultimate storehouse of the treasures of Zork.
     There are chests here containing precious jewels, mountains of
zorkmids, rare paintings, ancient statuary, and beguiling curios.
     In one corner of the room is a bookcase boasting such volumes as
'The History of the Great Underground Empire,' 'The Lives of the
Twelve Flatheads,' 'The Wisdom of the Implementors,' and other
informative and inspiring works.
     On one wall is a completely annotated map of the Great Underground
Empire, showing points of interest, various troves of treasure, and
indicating the locations of several superior scenic views.
     On a desk at the far end of the room may be found stock
certificates representing a controlling interest in FrobozzCo
International, the multinational conglomerate and parent company of
the Frobozz Magic Boat Co., etc.)~", 
    R"~(Treasury of Zork)~", 
    { }, 
    { "ODOOR"}, 
    room_funcs::nirvana(), 
    { RoomBit::rendgame, RoomBit::rlandbit, RoomBit::rlightbit } , 
    { RP(ObjectSlots::ksl_rval, 35) }),
